### ISSUE TITLE
postgresql app

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#106]
I'm using heroku at present, with the [postgresql add-on](https://elements.heroku.com/addons/heroku-postgresql).  As with everything on heroku, it's super-simple to set up, and the db is accessible via the [CLI](https://devcenter.heroku.com/articles/heroku-postgresql#using-the-cli) and also from within any node app via the [pg npm module](https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js).

Is anything approaching that possible yet with captain (in particular, access to a central db from any of a number of running node apps)?  If so, it would be great to have a simple guide.  If not, well, maybe in future?!

BTW thanks for this really promising set of tools!

**Comment by githubsaturn** [comment]
Of course, CaptainDuckDuck is totally capable of that!  You can simply click on "one-click" apps and select PostgreSQL and enter your configurations such as container name, username and password. Then Use pg np module to connect to the database. When you want to connect to DB, you have to use some environmental variables:
https://node-postgres.com/features/connecting
-  PGHOST=`srv-captain--xxxxx` where `xxxxx` is the postgres container name you entered when creating Postgres
-  PGPASSWORD=`secretpassword` again,  `secretpassword` is what you chose when creating Postgres container
-  PGDATABASE=`mydb`, database name you chose when creating Postgres container.

Note that since you run your Postgres on the same private network as your app, you do not need to enable SSL.


If fact CaptainDuckDuck is much more capable compared to Heroku, you can have private backend apps that can only be accessed via your own apps. See here: https://github.com/githubsaturn/captainduckduck/wiki/Complete-Webapp-Tutorial

**Comment by drmrbrewer** [comment]
OMG awesome.  Can't wait to dig into this further!  Thanks.
