### ISSUE TITLE
Docker Compose Support

### ISSUE THREAD

**Issue by angelopolotto** [githubsaturn/captainduckduck#11]
Can I configure and run a custom Docker Compose file with C.D.D (Captain Duck Duck)? I need that to build most of my applications but I don't like the complexity of the others tools like Kubernetes.

**Comment by githubsaturn** [comment]
Short answer: No.
More details:
- Docker compose (or even docker stack deploy) functionality is not exposed through docker API (this makes is impossible for Captain to communicate with docker)
- Docker compose is sort of abandoned by Docker in favor of swarm
- Docker compose is useful only to define the skeleton of your application. But once services are created, developers should be able to deploy them independently. 

All you need to do in order to convert your docker compose project to Captain project is to create micro services and deploy them independently. No docker compose file would be needed.

In Captain roadmap:
- Create an example to show how to convert a docker compose based app to Captain format
- Create an automatic convertor where you upload your docker compose file and it creates service placeholders for your micro services

**Comment by angelopolotto** [comment]
Thanks for the answer.
I got the ideia, I'll keep waiting for more news about those functionalities.

**Comment by JosXa** [comment]
It looks like this is (now?) a thing: https://docs.docker.com/compose/production/#running-compose-on-a-swarm-cluster

**Comment by githubsaturn** [comment]
Docker compose a configuration management tool. CapRover is also a configuration management tool. They can't co-exist.

However, you can use Docker compose format to bootstrap initial skeleton of an application. In fact this is how one click apps work. See here https://github.com/caprover/one-click-apps#repo-for-caprover-one-click-apps

**Comment by SaadBazaz** [comment]
Still need this, but for custom docker-compose files...

**Comment by josedev-union** [comment]
I wrote a simple gh action to allow multiple application deployment on Caprover. https://github.com/josedev-union/caprover-compose-action/tree/main
