### ISSUE TITLE
Error when adding apps with 3rd party Docker registry

### ISSUE THREAD

**Issue by dottodot** [githubsaturn/captainduckduck#110]
Since updating to the latest version I'm getting an error when adding apps, including 1click ones.

This is what's in the logs
```
captain-captain.1.c23uwns0y0ra@duck-test    | January 9th 2018, 6:33:52.909 pm    Docker Auth is found. Pushing the image...
captain-captain.1.c23uwns0y0ra@duck-test    | POST /api/v1/user/appDefinitions/register 500 409.576 ms - 21
captain-captain.1.c23uwns0y0ra@duck-test    | January 9th 2018, 6:33:53.211 pm    Error: Wrapped: unauthorized: authentication required
captain-captain.1.c23uwns0y0ra@duck-test    | Error: Wrapped: unauthorized: authentication required
captain-captain.1.c23uwns0y0ra@duck-test    |     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
captain-captain.1.c23uwns0y0ra@duck-test    |     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
captain-captain.1.c23uwns0y0ra@duck-test    |     at IncomingMessage.<anonymous> (/usr/src/app/src/docker/DockerApi.js:484:36)
captain-captain.1.c23uwns0y0ra@duck-test    |     at emitOne (events.js:115:13)
captain-captain.1.c23uwns0y0ra@duck-test    |     at IncomingMessage.emit (events.js:210:7)
captain-captain.1.c23uwns0y0ra@duck-test    |     at addChunk (_stream_readable.js:264:12)
captain-captain.1.c23uwns0y0ra@duck-test    |     at readableAddChunk (_stream_readable.js:247:13)
captain-captain.1.c23uwns0y0ra@duck-test    |     at IncomingMessage.Readable.push (_stream_readable.js:209:10)
captain-captain.1.c23uwns0y0ra@duck-test    |     at HTTPParser.parserOnBody (_http_common.js:140:22)
captain-captain.1.c23uwns0y0ra@duck-test    |     at Socket.socketOnData (_http_client.js:438:20)
captain-captain.1.c23uwns0y0ra@duck-test    | January 9th 2018, 6:33:53.211 pm    Error: Wrapped: {"message":"unauthorized: authentication required"}
captain-captain.1.c23uwns0y0ra@duck-test    | Error: Wrapped: {"message":"unauthorized: authentication required"}
captain-captain.1.c23uwns0y0ra@duck-test    |     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
captain-captain.1.c23uwns0y0ra@duck-test    |     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
captain-captain.1.c23uwns0y0ra@duck-test    |     at IncomingMessage.<anonymous> (/usr/src/app/src/docker/DockerApi.js:486:36)
captain-captain.1.c23uwns0y0ra@duck-test    |     at emitOne (events.js:115:13)
captain-captain.1.c23uwns0y0ra@duck-test    |     at IncomingMessage.emit (events.js:210:7)
captain-captain.1.c23uwns0y0ra@duck-test    |     at addChunk (_stream_readable.js:264:12)
captain-captain.1.c23uwns0y0ra@duck-test    |     at readableAddChunk (_stream_readable.js:247:13)
captain-captain.1.c23uwns0y0ra@duck-test    |     at IncomingMessage.Readable.push (_stream_readable.js:209:10)
captain-captain.1.c23uwns0y0ra@duck-test    |     at HTTPParser.parserOnBody (_http_common.js:140:22)
captain-captain.1.c23uwns0y0ra@duck-test    |     at Socket.socketOnData (_http_client.js:438:20)
captain-captain.1.c23uwns0y0ra@duck-test    | January 9th 2018, 6:33:53.212 pm    Error: Wrapped: 
captain-captain.1.c23uwns0y0ra@duck-test    | {"message":"unauthorized: authentication required"}unauthorized: authentication required
captain-captain.1.c23uwns0y0ra@duck-test    | Error: Wrapped: 
captain-captain.1.c23uwns0y0ra@duck-test    | {"message":"unauthorized: authentication required"}unauthorized: authentication required
captain-captain.1.c23uwns0y0ra@duck-test    |     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
captain-captain.1.c23uwns0y0ra@duck-test    |     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
captain-captain.1.c23uwns0y0ra@duck-test    |     at /usr/src/app/src/routes/AppDefinitionRouter.js:273:20
captain-captain.1.c23uwns0y0ra@duck-test    |     at <anonymous>
captain-captain.1.c23uwns0y0ra@duck-test    |     at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by githubsaturn** [comment]
- Do you use self-hosted Docker registry or a 3rd party one? 
- Were you on v0.4 before?

You can temporarily roll back to previous version if this turns out to be an actual bug.
```
docker service update --image dockersaturn/captainduckduck:0.4.0 captain-captain
```

**Comment by dottodot** [comment]
I'm using aws for the Docker registry. Yes i was on 0.4, do you want me to try rolling back to see if it fixes it. It's just a test server at the moment so can't do any harm

**Comment by githubsaturn** [comment]
Ok then, if it's not doing any harm, you can keep it until I do further investigation to see what the issue is. 

Thanks for reporting this.

**Comment by dottodot** [comment]
OK just reverted to 0.4 and it's working again

**Comment by dottodot** [comment]
Also I don't think it will be related but for some reason my ssh keys no longer work to connect to my server. It's might just be coincidence but seems to have happened since the update.

**Comment by githubsaturn** [comment]
It turned out that this is an issue with 3rd party username scoped providers. The problem has always been there (even `v0.4`). In `v0.4`, it silently fails to push the image, in `v0.5` it fails and correctly informs the user. The fix is to add the `/username` prefix to the image name. Will do that in `0.5.2` later this week.

This does not affect self-hosted registries.

**Comment by githubsaturn** [comment]
https://github.com/githubsaturn/captainduckduck/releases/tag/v0.5.3

**Comment by dottodot** [comment]
I've update to the lastest version and now get the error

```
Error
Push failed: {"message":"unauthorized: authentication required"}unauthorized: authentication required
```
does that mean I have a issue with the way I have my AWS registry setup? I'm not getting any errors when entering the remote registry on the dashboard page.

**Comment by githubsaturn** [comment]
Entering remote registry on dashboard simply "saves" the information. It does not connect to your remote. So no matter what you enter it always returns successfully.
PS: the reason that saving on dashboard is a bit of a long process is that Captain encrypts your auth data into [Docker Secrets](https://blog.docker.com/2017/02/docker-secrets-management/)

For your registry info:
- Host: this is the domain name for your registry. It something like: `docker-registry.somesite.com` or `something.something.com:5000`. Note that it does not have any http or https, but it might have port.
- Username: this is the Docker registry username scope, it is NOT your email. For example for CaptainDuckDuck `https://hub.docker.com/r/dockersaturn/captainduckduck/` the username is `dockersaturn`
- Password: self-explanatory.


I have tested the implementation with 
- https://treescale.com/
 This works great - except it takes 30-60min for your repo to show up on your dashboard once you push it. 
- https://canister.io/
 This one is quick. But their implementation requires youto create the repo name on dashboard before you push it to `canister.oi` otherwise you get a cryptic authentication error. I had to google the error to hunt down what is causing it. Your image names are in this form `img-captain--yourappname`

**Comment by dottodot** [comment]
So do you know if it would work with Amazon Elastic Container Registry?

I have a URi of `aws_account_id.dkr.ecr.region.amazonaws.com/dockerimages` and I've created a user will full access and that's what I've entered for the username and password, but that didn't work.

I also tried changing the host to `aws_account_id.dkr.ecr.region.amazonaws.com` and entering `dockerimages` as the username but that also fails

**Comment by githubsaturn** [comment]
I don't see any reason that it shouldn't work. Have you tried the command line approach to see if that succeeds?
```
docker login
docker pull hello-world
docker tag hello-world URL/USERNAME/some-great-name
docker push URL/USERNAME/some-great-name
```

**Comment by githubsaturn** [comment]
I played with Amazon Elastic Container Registry to see if it works. The short answer is no, but here is the synopsis: 

First, in order to get your docker login credentials, you should follow these steps:
![image](https://user-images.githubusercontent.com/10582082/34857036-8bdb702c-f6fd-11e7-85d0-8c3745962298.png)
When you do that, it prints a login command saying that the username is `AWS` and the password is a very long random set chars. You can log in successfully. Anyways, so far so good. But the issue is when you want to push the image, CaptainDuckDuck uses standard Docker image format of `DOCKER-REGISTRY-URL:PORT/USERNAME/IMAGE-NAME` (similar to docker hub and other providers), however, AWS doesn't like this because it does not let you have any uppercase letter in the image name, guess what the username is `AWS`!! If you use `aws` as the username when sending authentication, it fails in authentication step!!! Oh dear AWS! Clearly, they made it such that it works great with their own elastic container system, but f... everyone else.

Removing username from the image name fixes the issue with AWS, but breaks every other registry! Perhaps, I'll add an option to manually change whether this username should be part of image name or not.

**Comment by dottodot** [comment]
Thanks for looking into it, I had got to the point of get the `AWS` username and password but got the same error which confused me. Aws never makes it easy.
