### ISSUE TITLE
Nodes captain and wiki page

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#111]
Would it be possible to add a bit more clarification to the Captain and wiki pages for adding a new Node?  

I have one node, and I'm trying to add a second node.  On the Caption page for Nodes, when adding a new node, there are fields for:

Captain IP Address (as seen by remote) -- *is this the same IP address as for the first node??*
SSH Private Key -- *of which node?  how do I find this?*

And under the info for the first node, it has:

Type: Leader

But the wiki talks about `worker` and `manager` types... is `leader` different to `manager`?

And should I enter `worker` in the details for the second node I'm adding?

**Comment by githubsaturn** [comment]
There is already a page on wiki. But I'll add more details 👍 

https://github.com/githubsaturn/captainduckduck/wiki/Server-Clustering-and-App-Scaling#run-multiple-servers

**Comment by githubsaturn** [comment]
Details added.

**Comment by drmrbrewer** [comment]
Thanks @githubsaturn!  That's helpful.  One follow-up:

> Private SSH key: this is the SSH key that you use to SSH to your second server. On Linux, it's on /home/yourusername/.ssh/id_rsa

I'm a bit confused.  The SSH key that we'd normally use to enable SSH'ing to the second server is the **public** key of the host from which you are SSH'ing to the second server.  But the nodes page is asking for the **private** key... of the **second server**?  So to get that, we'd ssh on to the second server, and copy what's in `/home/yourusername/.ssh/id_rsa`, which is the **private** key?

**Comment by githubsaturn** [comment]
https://superuser.com/questions/370028/where-are-my-private-public-ssh-keys-on-unix

Private keys and public keys are in pair. i.e., for each private key, there is a public key.

Let's say there is this pair
- Private key: AAA
- Public key: BBB

You need to provide AAA in order to connect to a server whose public key is BBB. When you create a new server, you give digitalocean your public key so they can copy the public key BBB to your server. **The private key AAA sits on your computer.** Depending on your OS, just google "where is private key ubuntu" or do the same for windows and MacOS
