### ISSUE TITLE
Question re server location

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#120]
This may well not be specific to captain (forgive me) but there may be something in how captain does things which makes it relevant here.

Providers such as vultr and digitalocean allow you to specify a location for a server when you set it up.  This is all well and good, but how does one properly take advantage of this?  Let's say my app needs six servers to cope with the load.  Captain offers an easy way to set this up by clustering them.

But presumably the incoming requests are still being received at the leader node, so even if I set up my six servers in six different locations, if the leader node is in London then all requests have to go there anyway... so there is no real advantage?  But if the request is routed from London to another server in Sydney for handling, then the response will be sent from there, so there is some benefit for users in Australia?  But if the user is in London, then there is actually a cost in receiving a request in London, routing it to Sydney to handle, and then sending the response back to London?

To what extent is the location of the incoming request taken into account when distributing requests to the available servers?  Do you have any hints and tips about how it's possible to choose server locations and set things up properly... or at this level (without having a degree in distributed server architectures) is it really just a case of keeping things simple, by setting up all your servers in the same location and just putting up with any geographical issues?

**Comment by githubsaturn** [comment]
Generally speaking, you kee your servers where the majority of your users are. 

As you mentioned, since the leader node who receives the original request, it doesn't matter where other servers are. In fact, you want to keep them close to your leader node to reduce latency. 

As for geographical issues, one thing that most companies do is to use 3rd party CDN services such as Akamai as they have servers literally everywhere. CDNs are generally used for static assets. Unless you're as big as Facebook, that should be enough. Fo mid size companies, the common practice is to use servers (both computation and DB) in one location and use a CDN for static assets.
