### ISSUE TITLE
Remove Nodes / Disable Self Hosted Registry?

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#137]
Is it possible to disable the Self Hosted Registry after enabling it?  I know this is going to cause problems if you have a cluster set up, but if you want to remove a node and go back to a single-node setup then you might also want to disable the registry.  It's possible to disable / delete other stuff (e.g. app, monitoring) so disabling registry via the Console would be nice.  That being said, I see it's also not possible to remove a node currently... on the Nodes page there is no such option.  Maybe it's planned for the future?  And maybe the Self Hosted Registry stuff should be on the Nodes page, since it's only really needed with multiple nodes?

**Comment by githubsaturn** [comment]
Disabling Docker registry causes a lot of issues once enabled. All app images pushed to docker registry will be unavailable once the registry is dead. In nutshell, one should never do this in a production environment.  Other components can be turned off because they are independent. NetData doesn't interfere with anything else. 

Theoretically, I can add removal of the nodes to Captain. But I won't be doing it as it will snowball into a unmanageable monolithic duplication of Docker API. What I mean by that is this: Docker has a zillion commands. For example, when it comes to nodes, you can add labels to nodes, you can add them, remove them, you can upgrade a worker to a manager, you can change the SSL certificate and many more things. Check out Captain Design Principle in wiki. Captain does not / will not be a duplicate for Docker. There is no point it that. 

Back to your point specifically about removal:
- Simply remove your second server. i.e., from your provider's control panel kill the server. Then, you will see the node as a "dead" node in Captain dashboard and docker swarm automatically removes all instances that were running on that node and move them to the main node. **Zero work required on Captain**!
- Having a dead node has no harm to the performance of your cluster. But if it bothers you, simply ssh to your server, and run `docker node ls`, copy the id of the dead node and run `docker node rm id-of-dead-node`. It's quite straightforward.

**Comment by drmrbrewer** [comment]
Thanks for the excellent and informative answer. 

> Disabling Docker registry causes a lot of issues once enabled. All app images pushed to docker registry will be unavailable once the registry is dead. In nutshell, one should never do this in a production environment. 

Sure, I wasn't suggesting that it would simply be removed.  Before removing it, isn't it possible to create a container based on the actual image (from the docker registry), rather than based on a reference to the image in the docker registry... presumably this is what happens without a registry?  Then delete the old container.  When that is done for all such images in the registry, the registry itself can be removed?  Maybe it's just me, being a neat freak, but I like to know that I can get back to a previous state, if I wanted to, before making a change.

> Theoretically, I can add removal of the nodes to Captain. But I won't be doing it ... Captain does not / will not be a duplicate for Docker

Fair enough.  Though it seems to me that, in this instance, since there is a node listed in the Nodes page as "dead", it would be nice to have a simple "remove" button that offered an easy way to clear it away... personally I don't like having any "dead wood" hanging around, where it can be avoided, and like to tidy things up.  This to me seems like one of those "simple" tasks that Captain is there to do... it's not an "advanced" task like changing SSL certificates etc.

Particularly, in this case the issue is visible in the dashboard, so it will prompt endless questions on here from those without much Docker experience (like my question)... "I see a dead node listed... how do I get rid of it?".  I don't expect many users at this level of knowledge will see the node ID in the dashboard and think "hmm, how do I change that?".   For more hidden/advanced features of docker, these users won't know that there is even a question to ask :)  Just thinking about the future workload for you and any other contributors to this project.

At the very least, maybe just a brief explanation next to a dead node about how to remove it using the docker CLI?

Anyway, just some thoughts.  Still loving captain... thanks again.
