### ISSUE TITLE
Deploying a php-app Using github

### ISSUE THREAD

**Issue by aswinsatish** [githubsaturn/captainduckduck#144]
I am trying to deploy an php codeigniter app using Captain Duck Duck, this is working fine when using Tarball method. 
Later when i tried deployment using  Deploy from Github/Bitbucket/Gitlab, this is not working for me , just a node docker comes up my application is not getting deployed

I extracted the working tar copy and created a git repo for the same and tried deploying as per the instructions given in the github repo

Kindly help to sort this out.
Thanks

**Comment by githubsaturn** [comment]
Two questions:
1:
Have you tried `captainduckduck deploy` method? Does this work?

2:
Deploy from Github requires a push event. After setting up your repo info, you need to make a commit and push your code to Github in order for deploy to happen. Just adding your webhook information does not deploy the code. Does this help?

**Comment by aswinsatish** [comment]
1:
Have you tried captainduckduck deploy method? Does this work?

   No i will try this method

2:
Deploy from Github requires a push event. After setting up your repo info, you need to make a commit and push your code to Github in order for deploy to happen. Just adding your webhook information does not deploy the code. Does this help?

I have committed and pushed the code after depoyment, unfortunately it did not work. I will try the above method and revert

**Comment by aswinsatish** [comment]
Also if using captainduckduck deploy method does webhook work?

**Comment by githubsaturn** [comment]
Deployment methods are independent. You can use CLI for one deployment, the next version can be done using tarball file, the next can be done using GitHub webhooks.

**Comment by aswinsatish** [comment]
I have tried all the 3 methods mentions.:
1)  Captain Duck Duck Deploy Method:
          Cloned the git repp and used cli method to create the app, this works well and my app is getting 
          deployed

2)     Tar ball method:
             Created a tar archive with captain definition file and uploaded from web interface of 
             captainduckduck. This also works well and code is getting deployed

 3)  Git Method
           Configured the repository and credentials as said and configured the webhook url in git repo 
           settings. But on git push the app is not getting deployed.

Please help to sort out the git method as this helps in more continuous deployment of application

**Comment by githubsaturn** [comment]
Let's start with the simplest case and gradually evolve it to your own repo to see where it break.
- Start with a "Public Repo" on Github. Grab the PHP sample project [from here](https://github.com/githubsaturn/captainduckduck/tree/master/captain-sample-apps), then un-tar it and push it to your own Github account as a separate repo. Use your username, password, repo and branch; for repository use `github.com/username/reponam` schema. Set your webhook and perform a `git push`. See if deploy is successful. If yes, proceed to next step.
- Change the repo to private. Make a change in the repo, commit and push. If successful, proceed to next
- Change the code from the sample code to your own code, make a change, commit and push.

If you do above steps, you'll find out at what step it breaks. If you need more details, here is how to debug it:
- SSH to your captain server and run `docker service logs --since 10m --follow`, keep the window open.
- Push your repo and watch the output logs from Captain, if there is any error it appears there.

**Comment by aswinsatish** [comment]
Hello,
Tried deploying php sample project for the git repo, nothing is coming up. On saving the app details with github credentials, a sample nodejs docker comes up whatever captain definition file is in the repo.
I also tried pushing the changes to git but unfortunately no changes are happening in cdd server and no docker image is build.
On checking the github webhook section, i can see that webhook is successfully triggered.

docker logs --since 10m --follow d83b53cc1f3d, is not showing any logs other than the npm logs which was used to bulid the first docker nodejs image

Any help is appreciated.

**Comment by Rusfighter** [comment]
Using 2 factor authentication for github?

**Comment by githubsaturn** [comment]
I have two factor enabled and still able to use this method. I just tested everything from scratch and it works just fine. Here is my logs obtained via `docker service logs captain-captain --since 10m --follow` 

```
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | GET /checkhealth 302 0.379 ms - 72
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | GET /checkhealth 200 1.316 ms - 36
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | GET /checkhealth 302 0.349 ms - 72
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | GET /checkhealth 200 1.191 ms - 36
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | GET /checkhealth 302 0.429 ms - 72
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | GET /checkhealth 200 1.696 ms - 36
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | POST /api/v1/user/webhooks/triggerbuild?namespace=captain&token=.eyJkYXRhIjp7InRva2VQ1LWdGFpbiJ9LCJpYXQizjHkwwyGgnQ4816oZSmtVLBfwxk 200 14.159 ms - 2
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:38.684 am    Creating image for: qeqe
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:39.525 am    Building docker image. This might take a few minutes...
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:40.105 am    Cleaning up up the files... /captain/temp/img_tar/registry.sw.captainduckduck.com:996/captain/img-captain--qeqe/8  and  /captain/temp/img_raw/registry.sw.captainduckduck.com:996/captain/img-captain--qeqe/8
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:40.139 am    Docker Auth is found. Pushing the image...
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:40.910 am    Ensure service inited and Updated for: qeqe
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:40.919 am    App definitions retrieved
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:40.919 am    Check if service is running: srv-captain--qeqe
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:40.926 am    Service is already running: srv-captain--qeqe
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:40.927 am    Updating service: srv-captain--qeqe with image: registry.sw.captainduckduck.com:996/captain/img-captain--qeqe:8
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:42.969 am    Updating Load Balancer
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:42.969 am    Locking NGINX configuration reloading...
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:42.991 am    SUCCESS: UNLocking NGINX configuration reloading...
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:42.991 am    sendReloadSignal...
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | January 26th 2018, 2:04:43.002 am    Kill HUP Container: a102c6126c55e189cf75869e2f1e12110c5ba21af3a4ab25780d59653696b5cd
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | GET /checkhealth 302 0.436 ms - 72
captain-captain.1.jlmfl325vi07@scw-5e9dd2    | GET /checkhealth 200 2.059 ms - 36
```


Notice the line `POST /api/v1/user/webhooks/triggerbuild.....`. This indicates that GitHub sent a request to Captain server to trigger a build. If you don't see this line, it means your GitHub configurations are wrong. On GitHub, go to your repo -> Options -> Webhooks -> Add Webhook

For Payload URL, use the URL that Captain gave you: `https://captain.root.domain.com/api/v1/user/webhooks/triggerbuild?namespace=captain&token=I1NiIsInR5cCI6IkpXVCJ9`

Content type: select JSON or WWW-FORM-ENCODED. I use `WWW-FORM-ENCODED`

Secret: nothing, leave this empty. They save and perform `git push` while doing `docker service logs captain-captain --since 10m --follow` on your server. You should see a POST request.


------------


Also, to make sure that the event is received by Captain, you can go to your webhooks on GitHub and see "Recent Deliveries":
![image](https://user-images.githubusercontent.com/10582082/35422069-93db3556-01fb-11e8-9386-97bbec4836ca.png)

You should see a `200` response.
