### ISSUE TITLE
413 Request Entity Too Large on deploy => changing captain config breaks captainduckduck

### ISSUE THREAD

**Issue by mbariola** [githubsaturn/captainduckduck#168]
What is the problem?

captainduckduck deploy of a big site leads to such error. I have tried changing the captain config client_max_body_size from 300 to 500, and that broke my captainduckduck. I had to reinstall a server snapshot.
I guess that the big issue is CDD breaking on such modification without being able to recover, but maybe I was fiddling the wrong value or doing it the wrong way.

If applicable, content of `captain-definition` file:

 {
  "schemaVersion" :1 ,
  "templateId" :"php/7.0"
 }

Steps to reproduce the problem:

Install Captainduckduck server and client as per docs
captainduckduck setup
create a wordpress app on server whose TAR is around 331 Mb.
captainduckduck deploy  - get error
try to modify client_max_body_size from 300 to 500
captainduckduck breaks and is inaccessible from either client or web interface

Answers to the following questions where applicable:
- Your OS and version?
Ubuntu Linux 16.04, updated

- RAM?
2 GB

**Comment by githubsaturn** [comment]
> captainduckduck breaks and is inaccessible from either client or web interface

Does it mean you cannot connect to it or it's giving you some sort of nginx error? 



Anyways, I just tried it and it seems to be working fine. What configuration did you change? You should change the one on settings page that says: `Captain Config Located at: /etc/nginx/conf.d/captain-root.conf`

I simply change this line: `client_max_body_size 500m;` 

Did you also change this line?


If so, let's get some more logs to see what happened in your instance. To do so, SSH to your server and enter
```
docker service logs captain-nginx
```

Then go ahead and make the change from 300m to 500m. Wait for 10-15 seconds and see what kind of error comes out in the nginx logs. Please copy and paste the logs here so that I can look into what's happening. 


If you don't see any error in nginx logs, try getting logs from Captain using:

```
docker service logs captain-captain
```

And see if there is any error showing up in Captain logs.

**Comment by mbariola** [comment]
Hello,
yes I changed just that line, but atm I cannot try again because after restore, I wanted to do a snapshot incurring in #169 , so I will try again once we sort that other one out. Thanks for your prompt help :-)

**Comment by githubsaturn** [comment]
Thanks @mbariola for reporting this. I was able to reproduce it with a really long domain name. 

It is fixed here:
https://github.com/githubsaturn/captainduckduck/commit/e81336c70a64b636f60124aabe5cc6a8b9b4554d

You have two options:
1- Wait until the next release (hopefully some time next week)
2- Once you set up your server and can access dashboard, BEFORE creating any app, go to settings and edit the nginx configuration :

```
server_names_hash_bucket_size 128;
```

Where to add it: `Base Config Located at: /etc/nginx/nginx.conf` Right after this line:
```
keepalive_timeout  65;
```

**Comment by mbariola** [comment]
Thanks for looking into it. Would there be a way to effect this change without having to remake the whole VM? (I cannot access the conf files from the web interface)

**Comment by mbariola** [comment]
In the end, I just deleted CDD server and reinstalled ... seems to work OK for now :-)

**Comment by githubsaturn** [comment]
In wiki you can find steps to uninstall the Captain. You also need to delete /captain folder. Then reinstall.
