### ISSUE TITLE
Issue when passwords do not match in serversetup

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#170]
I was doing a `captainduckduck serversetup`, and when it got to the password bit, I messed up and entered a confirmation password that did not match the first one.

    >> Passwords do not match

OK, but there doesn't seem to be any route forward now... no option to re-enter the password.  So I just did Ctrl-c to back out and try again.  But trying again on the same server, I get the following when entering the IP address:

	$ captainduckduck serversetup
	 
	Setup your Captain server
	 
	? Have you already installed Captain on your server by running the following line:
	mkdir /captain && docker run -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck ? Yes
	✖ Login...
	Something bad happened. Cannot connect to "http://xxx.yy.zzz.aa:3000/api/v1/login"
	{
	  "statusCode": 302,
	  "body": "Found. Redirecting to https://xxx.yy.zzz.aa:3000/api/v1/login",
	  "headers": {
		"x-powered-by": "Express",
		"location": "https://xxx.yy.zzz.aa:3000/api/v1/login",
		"vary": "Accept",
		"content-type": "text/plain; charset=utf-8",
		"content-length": "61",
		"date": "Thu, 08 Feb 2018 11:41:00 GMT",
		"connection": "close"
	  },
	  "request": {
		"uri": {
		  "protocol": "http:",
		  "slashes": true,
		  "auth": null,
		  "host": "xxx.yy.zzz.aa:3000",
		  "port": "3000",
		  "hostname": "xxx.yy.zzz.aa",
		  "hash": null,
		  "search": null,
		  "query": null,
		  "pathname": "/api/v1/login",
		  "path": "/api/v1/login",
		  "href": "http://xxx.yy.zzz.aa:3000/api/v1/login"
		},
		"method": "POST",
		"headers": {
		  "x-namespace": "captain",
		  "x-captain-auth": null,
		  "content-type": "application/x-www-form-urlencoded",
		  "content-length": 18
		}
	  }
	}

Not a big issue... I just spun up a new server and set it up on that, but thought I should report it anyway.

**Comment by githubsaturn** [comment]
If CLI craps out, you can simply login to the dashboard on the web with the default password `captain42` and change your password in the settings. 

serversetup doesn't work because your server is already fully set up and ready to go. So, if something went wrong during password change, do these:
- Go to the web dashboard and change your password
- Use login command on CLI to attach your CLI to server, simply run `captainduckduck login`. This is also the command you can use to login to an existing server on a new dev machine.
