### ISSUE TITLE
Disk cleanup question

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#180]
Usually I restart a service (app) by hitting `Save & Update Configuration` in the app settings on the Console.  

If I do the following to clean up on the server:

    # docker container prune --force && docker image prune --all --force

and then do a `Save & Update Configuration` again, the app/service fails to restart.  Is this expected?  I have to re-deploy the app again.

And how do I do that for a one-click app like postgres after a cleanup, since there is nothing to re-deploy to get things back to normal?

**Comment by drmrbrewer** [comment]
@githubsaturn Ironically, exactly this has just happened :)  I think the server must have restarted itself or something, leaving all of my app-based services showing `REPLICAS` of `0/1`, except for the one mentioned in my OP which I had already re-deployed.  That survived whatever event happened at the server, and was showing `REPLICAS` of `1/1`.  I re-deployed all apps, and `REPLICAS` for those is now back to `1/1`.

But my postgres service is still showing `REPLICAS` of `0/1`, and I'm not sure how to recover from that... please help!

Also, is this a danger of doing a disk cleanup as per the above (and as per [the wiki](https://github.com/githubsaturn/captainduckduck/wiki/Disk-Clean-Up))?  Does it leave the service vulnerable to some event like this?  BTW I am certain that when I did the disk cleanup, all were at `REPLICAS` of `1/1`.

**Comment by drmrbrewer** [comment]
OK I managed to get the postgres service back up and running (I remembered [this post](https://github.com/githubsaturn/captainduckduck/issues/156#issuecomment-362112835)):

    $ docker service update --image postgres:latest srv-captain--postgres

But I'd be interested to hear your view on whether doing a disk cleanup might have led to this, or whether it's unrelated.

**Comment by githubsaturn** [comment]
I'll look into this and will let you know.

**Comment by drmrbrewer** [comment]
Thanks for looking into it.  Looking back at the sequence of events, it does seem to be significant to me that:

(a) after a disk cleanup, a `Save & Update Configuration` failed to restart the app... is this what would happen after a server reboot, i.e. the service would try (but fail) to restart and be left on `0/1`?

(b) after the server event (reboot?) the only service (of mine) that recovered back to `1/1` was the one that I'd already re-deployed (captainduckduck, nginx and certbot were OK though)... seems to back up point (a)?

Think maybe I'll stop doing any disk cleanups until further notice.

**Comment by githubsaturn** [comment]
Excellet find! Turned out to be a Docker issue. Unfortunately, we cannot fix this as it's out of our hands. I added some notes to our wiki and reported the issue with Docker:
https://github.com/moby/moby/issues/36295

The reason that I haven't personally experienced this issue is that I typically use a local Docker registry. That way, after cleanup they get pulled back from the registry.

**Comment by drmrbrewer** [comment]
Thanks for following up on this.

I'm curious as to why the problem seemed to be limited to apps which I myself have created via the Captain console, i.e. why captainduckduck, nginx and certbot seemed to survive the image prune and restart...

**Comment by githubsaturn** [comment]
> And I can't see any changes to the disk cleanup wiki page.

Doh... Forgot to save the page. Thanks.

> Also, having to recover from a situation like this, where it is necessary to re-deploy the app in order to replace the lost image, prompts another question in my mind. One of my apps is deployed via a github webhook. I don't actually keep a local copy of the repo concerned (it is too big and is pretty much static... no further development ongoing), and instead make any changes directly on github, thereby triggering the webhook. But to force a new deploy, when no changes to the repo are required, I've been making some inconsequential change, like editing a dummy file in the repo. This doesn't seem too elegant, and I wonder if there is a way of triggering the webhook manually to force a re-deploy? Some sort of "manually trigger webhook" button in the Captain console would be nice.

Adding a button is easy. But it's only to address a bug. But in your scenario, you could have forcefully triggering build by sending a POST request to the webhook URL. Any POST call to that URL forcefully triggers the build. You can use simple CURL to issue that POST request:
```
curl -d "dummyparam=dummyvalue" -X POST http://YOUR_WEB_HOOK_FULL_URL
```

**Comment by githubsaturn** [comment]
> I'm curious as to why the problem seemed to be limited to apps which I myself have created via the Captain console, i.e. why captainduckduck, nginx and certbot seemed to survive the image prune and restart...


Those are not locally built images, they are hosted on Docker hub.

**Comment by Turab** [comment]
So it has been years but this issue stays unsolved? We still can't remove unused images if we don't have a Docker registry, can we? I have tried several apps which I just removed after some demonstration. Now their images reside in the app server for eternity and I can not remove them; because if I ever dare, Caprover and all the running apps break. Captain also can't remove them through the UI.

And docker log is full of lines like this;
cleanup: failed to delete container from containerd: no such container
msg="logs call failed" error="failed getting container logs: No such container:

**Comment by githubsaturn** [comment]
Images that CapRover UI cannot remove are either directly or indirectly being used.

>So it has been 3 years but this issue stays unsolved? 

The original Docker issue is here: https://github.com/moby/moby/issues/36295
There is nothing that CapRover can do about this.

**Comment by Turab** [comment]
That might suggest the existence of another bug. Because I am sure that those images are not used, as they don' have containers and their apps are deleted from the UI and their volumes are deleted from the CLI. I have never manually made any changes neither on containers nor on images. But some applications which I installed just for testing for only a couple of days and then deleted still has images which are never used and never removed. If there is something I can contribute to the solution, please let me know so I can share.

As I said, there are some log entries which complain that there are dead containers. All I did was create a one-click app, test it for several days, then delete the app through the UI. Was there anything more I should have done?

There must at least be a way which would let me untie those images from dead containers and then remove them.

**Comment by gschurck** [comment]
@githubsaturn What do you think about this custom solution ?

**Comment by githubsaturn** [comment]
I personally don't have much experience with that. But i know some people use that solution 
https://github.com/caprover/caprover/issues/457#issuecomment-532245598
