### ISSUE TITLE
Limit dashboard access by IP address

### ISSUE THREAD

**Issue by j7an** [githubsaturn/captainduckduck#183]
I tried modifying /etc/nginx/conf.d/captain-root.conf using the dashboard GUI to limit access to the dashboard to only my IP address. Unfortunately it caused 403 error and the Nginx container to continuously restart. So there was no way to restore the .bak file by entering the Nginx container via bash.

The .bak file for captain-root.conf in /captain was also empty. Not sure if its a bug when the .conf file is saved and updated but get stuck in a reboot loop.

I used the following format to limit by IP to the dashboard:
```
location / {
  allow XXX.XX.XX.XX;  ## Your specific IP
  deny all;
}
```

Found the Captain dashboard block and inserted the allow / deny above the `proxy_pass $upstream;` for both `location /` and `location /api/v1/user/appData`. Are the areas correct for limiting dashboard access by IP?

```
# Captain dashboard at captain.captainroot.domain.com
    server {

        listen       80;
        client_max_body_size 300m;

    <%
        if (captain.hasRootSsl) {
    %>
        listen              443 ssl;
        ssl_certificate     <%-captain.crtPath%>;
        ssl_certificate_key <%-captain.keyPath%>;
    <%
        }
    %>

        server_name  <%-captain.domain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        set $upstream http://<%-captain.serviceName%>:<%-captain.serviceExposedPort%>;

        # IMPORTANT!! Except proxy_read_timeout, this block should be same as location /api/v1/user/appData
        location / {
            allow XXX.XX.XX.XX;  ## Your specific IP
            deny all;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # temporary until build process becomes an asynchronous process
        location /api/v1/user/appData {
            allow XXX.XX.XX.XX;  ## Your specific IP
            deny all;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 120s;
        }

        # Used by Let's Encrypt and CaptainDuckDuck self health monitoring
        location /.well-known/ {
            root <%-captain.staticWebRoot%>;
        }
    }
```

**Comment by githubsaturn** [comment]
> The .bak file for captain-root.conf in /captain was also empty. Not sure if its a bug when the .conf file is saved and updated but get stuck in a reboot loop.

Those files are in `generated` directory. Every time Captain restarts, it clears that directory and re-create it using its configuration. You should never try to change those files as they are heavily managed by Captain and they will get overridden. 

As far as blocking access goes, short answer is you cannot. More details: nginx is part of a swarm which has its own subnet. To put it in a nutshell, the IP you're getting is the local IP, not your remote IP. Last time I read about it, people asked Docker to inject the remote IP address to any IP packet that comes to containers managed by Docker swarm, and Docker maintainers weren't too keen about it due to potential performance issues - as far as I remember. 
Note that regular containers do not suffer from this as they are not behind a virtual network adapter. To get external IPs passed to nginx, nginx needs to be managed not via Docker swarm, but as a plain container which makes it not as reliable. I don't think the benefit that this will give us compensate for the loss of reliability. Since Docker swarm is the future of Docker, I think sooner or later they will add support for this.
