### ISSUE TITLE
.php extension redirect (try_files directive) not working

### ISSUE THREAD

**Issue by vincelwt** [githubsaturn/captainduckduck#189]
Hi!

So I've set up a PHP app, and it is working fine.
Now I try to remove the .php from the url so

`http://example.com/page.php`
becomes
`http://example.com/page`

So I tried to modify the default Nginx conf of the app to add ` try_files $uri $uri.php $uri/;` in `location / {}` but no luck, all requests are returning a 404 error. I've also try with `rewrite ^(.*)$ /$1.php;` but same problem.

Do you have any idea why these directives is not working?

Also, the error indicates that the server running is Apache:
`Apache/2.4.10 (Debian) Server at ____ Port 80`

I'm a bit confused here, is actually Apache or Nginx running?

Also, my 2 cents, I think most php apps would beneficiate from removing the extension.php from the url, so it may be a nice addition to the default config.

Thank you!

**Comment by githubsaturn** [comment]
Have a look at this:

![image](https://user-images.githubusercontent.com/10582082/36388788-d960c9ec-1551-11e8-91cf-1885c5ca25c1.png)


nginx is the frontend engine. Once nginx receives a request, it verifies the SSL cert, finds out which app (container) the request belongs to, then forward that request to that container.

Inside PHP app container, there is an apache server which serves php file. In order to remove the extension, you need to modify apache config. One method is to change htaccess:
https://stackoverflow.com/questions/4026021/remove-php-extension-with-htaccess

**Comment by vincelwt** [comment]
Thanks for the answer.

For others facing the same problem, I had to rewrite the captain-definition with dockerfileLines to enable the mod_rewrite plugin:

Here my `captain-definition`:

```
{
	"schemaVersion" :1 ,
	"dockerfileLines": [
		"FROM php:7.1.10-apache",
		"RUN a2enmod rewrite",
		"COPY ./src/ /var/www/html/",
		"EXPOSE 80"
	]
}
```

and the `.htaccess`

```
RewriteEngine On

# Resolve .php file for extensionless php urls
RewriteRule ^([^/.]+)$ $1.php [L]
```
