### ISSUE TITLE
Rename app

### ISSUE THREAD

**Issue by wahkiz** [githubsaturn/captainduckduck#232]
Hello, 

Thanks for this fantastic software, it really helps when setting up my server on vultr. I am currently facing a problem where www would not be able to access my app. After searching the issues thread here, I found that I have to name my app "www" to resolve this, however my app is already named something else.

Is there a way to rename my app to www in order to make it accessible from the domain and www.domain? Or is there plans in the future of make subdomains management easier?

Regards
Calvin

**Comment by githubsaturn** [comment]
Apps do not have unique IDs other than their names. Things like SSL will break as they were generated for the original domain. Because of this, renaming apps is not on my radar as this creates complexity with very little added benefit. 

However, since app creation takes less than 15 seconds, and also since app deletion is supported, I suggest you do this:
- Create an app with the name of `www`
- Copy all your settings (environmental variables and etc) to the new app.
- Redeploy your app from your dev machine to `www`
- Delete your old app

**Comment by clementshimizu** [comment]
If you click on the app, you can connect an additional domain to an existing one for example you can have an app named mydreamapp on myserver.com and connect secondary domain 
www.myserver.com
