### ISSUE TITLE
Cannot update captain root domain v0.7.1

### ISSUE THREAD

**Issue by jialutu** [githubsaturn/captainduckduck#237]
Hi, I've found that with the recent version v0.7.1, I am unable to update the captain root domain, it just attempts to update it, but does not appear to do anything after a while. One of the ways I've found to be able to get around this is to first load the older v0.6.0 container and then update it to v0.7.1

**Comment by githubsaturn** [comment]
There was no change in v0.7 that could affect this. Once you enable SSL you cannot change domain, but it has always been like that. Can you repro this issue on a new server?

**Comment by jialutu** [comment]
Sorry for not being clear. The issue I am having is on the initial setup to add a captain root domain, where it just looks to be processing for a while and then nothing happens. 

I've been able to reproduce the issue again with a new captainduckduck server setup just now. 

Again, my current workaround is to setup first download v0.6.0 and then upgrade to v0.7.1 after the root domain has been added.

**Comment by githubsaturn** [comment]
Could be due to a weird firewall setting.

Can you please run `ufw disable` and retry?

**Comment by githubsaturn** [comment]
I was able to repro this if a firewall is blocking port 80 and port 443. Specifically, it's due to this change: https://github.com/githubsaturn/captainduckduck/issues/201

The change itself is necessary. However, previously, since it was behind the routing mesh, Docker magically bypassed the firewall, but now, the firewall is getting in the way. So, the issue is indeed firewall, at least in my case.

**To fix, just run** `ufw disable`

Having said that, firewall issues are hard to track for the end user. So I'll add a precheck during the installation phase in the next release, to make sure that port 80 and 443 are open.
