### ISSUE TITLE
Drupal 7 PDOException after deploy

### ISSUE THREAD

**Issue by Daweo93** [githubsaturn/captainduckduck#239]
Hello, 
I've created app for Drupal 7 and I used app example for php. After deploy I have following error:
```
PDOException: SQLSTATE[HY000] [2002] Connection refused in lock_may_be_available() (line 167 of /var/www/html/includes/lock.inc).
```
Everything on local instance works fine. Any idea whats going wrong?

If applicable, content of `captain-definition` file:
```
 {
  "schemaVersion" :1 ,
  "templateId" :"php/5.6.0"
 }
```

Steps to reproduction.
1. Take example app for php
2. Download Drupal 7 files from [here](https://www.drupal.org/project/drupal/releases/7.59)
3. Extract files and add them to GIT repository
4. Deploy app to created before captain app

**Comment by githubsaturn** [comment]
This issue is not related to Captain.

Drupal requires a database connection in order to work. You should create a MySQL database and add it to `/sites/default/settings.php` file in your Drupal. Note that if you use a one-click MySQL, your host will be `srv-captain--yourmysqlappname`, not `localhost`

See these links:
https://www.drupal.org/forum/support/installing-drupal/2016-10-20/d7-install-error-pdoexception-sqlstatehy0002002
https://stackoverflow.com/questions/32810095/drupal-pdoexception-sqlstatehy000-2002-connection-refused-in-lock-may-be-a
https://www.drupal.org/forum/support/post-installation/2009-02-07/how-to-change-mysql-password-inside-drupal
