### ISSUE TITLE
FTP

### ISSUE THREAD

**Issue by ivanthemeh** [githubsaturn/captainduckduck#249]
Am I missing it or Is there a way to setup ftp connection in the docs? I have searched through issues and docs and cant find any way to do this and I am fairly new to devops.

**Comment by githubsaturn** [comment]
Assuming that you can have SSH connection to your server, you can for sure use SFTP in the same way. For example, in FileZilla:

![screenshot from 2018-06-30 09-56-46](https://user-images.githubusercontent.com/10582082/42127356-f87ea482-7c4b-11e8-83a7-a3caf1535a23.png)


If you want to FTP to your apps (containers), you just need to know their volume path:
```
$   docker volume ls     # this will show you a list of disk volumes
$   docker volume inspect volume-name     # volume-name is found using the previous command.
```

Note that you cannot SFTP to an app without volume, because anything that is not in a disk volume is ephemeral, meaning that it does not survive container restart and it will always go back to the original state.
