### ISSUE TITLE
Deploy from GitHub ?

### ISSUE THREAD

**Issue by willwade** [githubsaturn/captainduckduck#25]
Is it possible to deploy an app on a GitHub commit? (Like heroku )

**Comment by fergyfresh** [comment]
Look up dokku. We could probably modify this to be dokku like (docker-like heroku deploy)

**Comment by githubsaturn** [comment]
Dokku is extremely limited to git. Most of the benefits that come with Captain is due to the fact that Captain is not limited to git. It uses git, but it's not limited to git. Things like deploy through web dashboard, one click apps and etc wouldn't have been possible if the architecture was limited to git. The last thing we want is limit ourselves to git like Dokku as that would mean losing everything else.

I guess what you meant was automatic deployment when you push to github, right? The good thing about Captain's generic REST API is that the requested feature is surely possible thorough some sort of adapter. I'll keep this issue open to see how many people actually need this! It requires some non-significant amount of work, so I'll put it in the queue if it's actually a feature that people need 😄

**Comment by willwade** [comment]
Awesome. You are right. I am looking for GitHub deployment. To be clear
it’s because sometimes I’m on my phone or others are on other machines and
they don’t need the entire tool chain to make a change. GitHub deployment
would be awesome.

**Comment by fergyfresh** [comment]
@githubsaturn but doesn't Github deployment also significantly limit this to git as well?

A random related question @githubsaturn Captain support event based triggers? Could we trigger a deploy on the Captain server via a Github webhook? Where-ish could I look for event based code? I'll look on my own, but if you get to it before I do any input would be great.

**Comment by githubsaturn** [comment]
We wouldn't limit deployment architecture to git. We will have an adapter for github. 

Answer to your second question is no. In fact, that's how I'm going to address the github deployment issue. Once implemented, it will work like this:

You push to github
Webhook calls captain saying a new commit is pushed
Captain pulls from github and build

**Comment by josegonzalez** [comment]
Just wanted to chime in with a few thoughts:

- Dokku isn't "limited to git". In fact, we support deploys of bare docker images and tarballs (alongside git). We just so happen to store the current state of your service within a repository on the server _if_ you choose to push code via git.
- You can support a "push to deploy" type system pretty easily using something like [sshcommand](https://github.com/dokku/sshcommand). If you wanted to vendor such a thing into `captainduckduck`, the code is relatively simple and should be able to be ported into nodejs. Once you have a codebase on the server, it's relatively simple for you to extract a tarball and build from there, same as how `captainduckduck` currently works.

Great project btw, hope your users get excellent value from it :)

_One of the  Dokku maintainers_

**Comment by githubsaturn** [comment]
Thanks for your note and clarification. I'll look into sshcommand. Sounds viable.
