### ISSUE TITLE
custom error page nginx during application deployment and settings updates.

### ISSUE THREAD

**Issue by clementshimizu** [githubsaturn/captainduckduck#254]
What is the problem?
When i redeploy an app there is a time during the deployment where requests fail and display 
timeline:
1) myapp.mydomain.com responds correctly to web requests
2) notanyapp.mydomain.com gets captainduckduck formatted index.html or error.html pages located at /captain/generated/static/default
3) deploy myapp
4) during the deployment phase myapp.mydomain.com responds with 
```
502 Bad Gateway
nginx/1.15.2
```
5) after a few seconds the server responds correctly with the the content in the myapp.

my question is: how do i get the error page during step 4 to be the error page that i see in step 2

 I have tried to edit captain-root.conf but the changes i make dont seem to apply to apps that i have defined during the swap only to subdomains that are not matching to apps.

content of `captain-definition` file:
i am currently using the default captain-definition files but changing them didn't seem to affect which error page shows.

**Comment by githubsaturn** [comment]
`captain-root` is for top-level configs. For your specific app:
- Go to your app's settings page.
- Click on the blue button "Edit Default Nginx Configurations" to see the nginx config for that particular app.
- Scroll down the bottom of the config, and add the following blocks:
```
        location / {
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /.well-known/ {
            root <%-s.staticWebRoot%>;
        }


        ############### ADD THIS PART:
        error_page 500 502 503 504 /error.html;
        location = /error.html {
                root   /usr/share/nginx/default;
                internal;
        }

```


Method 2:
If you want a custom error page, you can benefit from `nginx-shared` directory. This directory is located at `/captain/nginx-shared` on your server and is mapped to `/nginx-shared` in nginx container. Therefore, you can place a custom `index.html` in `/captain/nginx-shared` directory on your server and instead of 
```
        error_page 500 502 503 504 /error.html;
        location = /error.html {
                root   /usr/share/nginx/default;
                internal;
        }
```
do:
```
        error_page 500 502 503 504 /error.html;
        location = /error.html {
                root   /nginx-shared;
                internal;
        }
```

Read more: https://captainduckduck.com/docs/nginx-customization.html#custom-files-and-directories

**Comment by clementshimizu** [comment]
Thank you!  I will test this out!
Amazing tool!
