### ISSUE TITLE
documentation on how to duplicate webhook payload to trigger a build from terminal/bash/curl to allow for custom CI/CD

### ISSUE THREAD

**Issue by wolfejw86** [githubsaturn/captainduckduck#275]
IMPORTANT: DO NOT POST issues that are not specific to CaptainDuckDuck. Issues and questions related to Docker will get closed.

What is the problem?
Currently, I don't see a clear path to duplicate the webhook payload to trigger a build manually (ie, i want to trigger the build from a travis ci "after_success" event
It probably isn't terribly difficult, however after a bit of time with postman i couldn't get it to fully trigger.  It'd be nice if this was documented somewhere - ie "Send this payload with curl to trigger a build"
Is this possible?

**Comment by githubsaturn** [comment]
There is no duplication involved. It is simply a post request. You can manually invoke it with:

```
curl -d '{"dummykey":"dummyval"}' -H "Content-Type: application/json" -X POST https://captain.yourdomain.com/.........(your full webhook path)
```

If the build is not triggered properly, it usually means that Captain failed to grab your git repo. This can be due to variety of reasons such as wrong usename/password, and etc.

To get more details about a failed process, do the following:
- SSH to your server
- Run `docker service logs captain-captain --since 2m --follow`
- Leave the SSH window open and open a new terminal
- Run the curl command to trigger a build.
- View live logs on the SSH terminal window. This stream of logs should be very informative and give you some details about what has failed the build process.

**Comment by wolfejw86** [comment]
ah thanks, this is great!
