### ISSUE TITLE
Minimum size for Digital Ocean Droplet

### ISSUE THREAD

**Issue by rossvz** [githubsaturn/captainduckduck#28]
It may be worthwhile recommending a minimum machine size on digital ocean. I tried running a basic hello-world node app on the $5/mo box and received cryptic error messages when trying to run the `npm install && npm cache clean --force` step. Apparently it was due to the machine running out of memory as seen [here](https://github.com/docker/compose/issues/1554). I increased the size of the droplet to the $10/month and deploy seems to work

**Comment by sah2ed** [comment]
@rossvz did you try increasing the swap size before trying with a larger droplet?

There's a related [npm issue](https://github.com/npm/npm/issues/3867) and the fix was to increase the swap to twice the RAM of the droplet.
DO instructions are [here](https://www.digitalocean.com/community/tutorials/how-to-configure-virtual-memory-swap-file-on-a-vps).

**Comment by githubsaturn** [comment]
Thank you guys. I've added some notes to tutorial
https://github.com/githubsaturn/captainduckduck/commit/3514c615df07eaf3cd7762df96508ac91c365563
