### ISSUE TITLE
Mongo replica set

### ISSUE THREAD

**Issue by dottodot** [githubsaturn/captainduckduck#30]
Hello, just come across CDD and it looks like it will meet my needs. The only thing I'm unsure on is if it's possible to deploy a mongo replica set. I can't see a obvious way of doing it, but I've only fired up 1 server so not sure if it becomes a option on a cluster.

**Comment by githubsaturn** [comment]
My experience with MongoDB is limited to simple applications. But as far as I know, MongoDB replica set is just a few separate mongodb instances that are somehow connected to each other. The way to do this, is to start 3 mongodb containers. Then mongo shell into them, and run replica connection commands.

Have a look at 
https://medium.com/@kalahari/running-a-mongodb-replica-set-on-docker-1-12-swarm-mode-step-by-step-a5f3ba07d06e
and 
https://towardsdatascience.com/how-to-deploy-a-mongodb-replica-set-using-docker-6d0b9ac00e49

Note that in both articles it is assumed that MongoDB containers are created from scratch using Docker. Those parts of the articles are not applicable for you as Captain automatically creates the mongodb instances for you. You just need to run some mongo shell command to connect the separate containers to create a replica set.

**Comment by dottodot** [comment]
OK so making manual changes on the server won't mess things up. For example I would need to make sure each mongo container was on a separate server by using --constraint

**Comment by githubsaturn** [comment]
Exactly. One of the main design criteria that I had in mind when started CaptainDuckDuck project was to allow users to make manual modifications as they wish. General rule of thumb is:
If a property is not exposed by CaptainDuckDuck, then user is allowed to change it without causing any problems.

**Comment by dottodot** [comment]
Thanks that's great, and I really like that approach. Might be worth adding something to the wiki about it just so it's clear to others like me.

**Comment by githubsaturn** [comment]
@dottodot 
Just realized that I gave you wrong information about `contraints` tag.  Sorry.

Correct answer:
So for apps with persistent data, Captain enforces a nodeId as constraint, once you assign a persistent directory to that container. Otherwise your persistent data will be lost if docker moves your container to another node. 

I'll add an editable nodeId field to apps with persistent data to allow user to change the containst. Of course, I need to add a bold warning explaining that doing so will cause all your persistent data to get reset. 

Additional potential change that I might do:
When creating database container using one-click form, I'll add an optional nodeId field.

This should address the use case, correct?
I'll get this out in next few days :+1: 

---- 
PS: As a temporary solution for now, you can just edit `/captain/config.conf` file and correct the nodeId fields (if any). Then go to your apps page, and just click on "Save Configuration and Update"/

**Comment by dottodot** [comment]
@githubsaturn From my current understanding I think your proposed solution of being able to assign the nodeId when creating a database container would work well. 

I think it might be better not to have the option to be able to edit it afterwards though to avoid any accidental changes that would result in the loss of data, and as renaming the nodeId would reset the data you may as well just create a new database and delete the old one.
