### ISSUE TITLE
Changing Root Domain

### ISSUE THREAD

**Issue by etienne-dldc** [githubsaturn/captainduckduck#312]
Hi 👋 

I know that the root domain cannot be chnaged once https is activated but I would like to know if there is a way to do it manually ?
From what I understand it should be possible to delete all HTTPS related content / settings and go back in an unsecure mode using the IP + Port, change the root domain then activate HTTPS again

Is this possible or I ma missing something here ?

**Comment by githubsaturn** [comment]
It is possible, but we intentionally disabled it as it's a high risk operation. In general, one shouldn't need to change the root domain as there is always an option to connect new domains to the app.

Having said that, to manually change the domain, you should edit `/captain/config.conf` and change "all" forceSSL and EnableSSL  values to false. Then you should be able to go `HTTP://captain.yourcurrentroot.com` and then change the root. Then re-enable everything. Keep in mind that this will completely break your cluster if you're using a self hosted docker registry as the images are being referenced to your current registry domain. In short, this is a very high risk operation and try to avoid doing this in production environment.

**Comment by alexander-potemkin** [comment]
for the future references - it's `/captain/data/config-captain.json` now.
It also seems that `sudo service docker stop`, do the config change, and `sudo service docker start` works better.

**Comment by githubsaturn** [comment]
This is no longer needed actually. You are now able to change the root domain from the UI.

**Comment by alexander-potemkin** [comment]
If you were lucky enough to do it before the actual move... But if not, that would be of help, I guess?

**Comment by smkamranqadri** [comment]
> sudo service docker start

I am not the lucky one, mine was expired and trying to do but it's not working.

**Comment by smkamranqadri** [comment]
oh it's working, I need to wait a little bit longer.

**Comment by drmrbrewer** [comment]
Is there a step-by-step guide to changing the root domain?  I understand from the above that you can now do this from the dashboard, but it's still a risky and complicated process (hence it would benefit from some guidance)?  I'd like to change my root domain from `captain.aaa.bbb.com` to `captain.xxx.yyy.com` (or even `captain.abc.xxx.yyy.com` based on [this guidance](https://caprover.com/docs/best-practices.html#hidden-root-domain)).  What are the gotchas to avoid (e.g. relating to re-enabling SSL)?  Since this would be on a production server (I know, not recommended), if things go belly up can it be recovered by backing up and re-using the `caprover-config.json` file?

**Comment by githubsaturn** [comment]
There is no step-by-step guide. You can simply change the root domain via the dashboard. 
In terms of issues that you might encounter, the SSL certifications are probably the most important thing. Especially if you have a large number of apps. Anything more than 20 apps is going to cause a problem. But other than the main domain, all other connected domains are going to work just fine.

**Comment by drmrbrewer** [comment]
@githubsaturn I think the difficulty is not knowing how much is handled by dashboard feature and how much is a manual process afterwards.

For example, I can't recall how SSL was enabled on the root domain itself when this was originally set up.  I assume it was handled by `caprover serversetup` which was run in [this step](https://caprover.com/docs/get-started.html#step-3-install-caprover-cli)? 

So if my current root domain is `something.mydomain.com` and I currently access the dashboard via `https://captain.something.mydomain.com`, after using the dashboard UI to change the root domain to `something.myotherdomain.com`, will it set up SSL so that I can access the dashboard right away via `https://captain.something.myotherdomain.com` or is there another step for that?

It's also confusing why "anything more than 20 apps is *going to* cause a problem"... why is it any more of a problem having 25 apps compared to 5 or 15 (I have many more than 20 apps)?  Just because there are more apps to reconfigure individually after?  

Is this just a case of hitting `Enable HTTPS` on the URL for each and every app... i.e. the "default" URL `http(s)://myapp.something.myotherdomain.com`?  Any custom added domains should still be OK (including HTTPS)?  

In my case, the "default" URL for any app is not used directly anywhere... for all my apps I've added a custom URL without the `something`, i.e. I have (at least) the following two URLs for each app:

`https://myapp.something.mydomain.com` (default)
`https://myapp.mydomain.com` (custom)

I never use the default one (though I have enabled https anyway for good measure)... I only use the custom one.

So does this mean I should be able to use the dashboard UI to change root domain without too much of a headache?  The dashboard itself will load OK via https under the new domain right away, and I can (if I wish) go into each app (at my leisure) via the new dashboard and enable https on each app (for good measure)?

Thanks, really appreciate any guidance here.  And sorry for acting dumb, I just don't want to make any incorrect assumptions and end up breaking it irretrievably!

**Comment by githubsaturn** [comment]
> So if my current root domain is something.mydomain.com and I currently access the dashboard via https://captain.something.mydomain.com, after using the dashboard UI to change the root domain to something.myotherdomain.com, will it set up SSL so that I can access the dashboard right away via https://captain.something.myotherdomain.com or is there another step for that?

In normal scenario, it does everything automatically. So you don't have to do anything. But like anything else, any stage can cause an error. Worst thing that can happen is that SSL cert isn't issued. So you can use use `http://` and manually use the dashboard to click on `ENABLE SSL`. 


> It's also confusing why "anything more than 20 apps is going to cause a problem"... why is it any more of a problem having 25 apps compared to 5 or 15 (I have many more than 20 apps)? Just because there are more apps to reconfigure individually after?

Let's Encrypt has a daily limit of how many SSL it can issue per day, it's not a CapRover limitation.


> Is this just a case of hitting Enable HTTPS on the URL for each and every app... i.e. the "default" URL http(s)://myapp.something.myotherdomain.com? Any custom added domains should still be OK (including HTTPS)?

Like I said, everything is handled for you. In case of an error, you'll have to manually click on Enable HTTPS, unless you hit the Let'sEncrypt limit, which then results in you having to wait a bit before retrying. Custom domains are fine. They are not impacted.


Even if you break everything, you can just manually edit the config file and revert to the old root domain. Things will continue to work as before.

**Comment by drmrbrewer** [comment]
Thanks, that's really helpful.  It gives the reassurance to proceed, understanding a little more about what should happen, and also what might not happen in certain circumstances.  Also good to know that it's possible to backup the original config file and just revert to that if things go wrong.
