### ISSUE TITLE
Error when build through cli - Code 137

### ISSUE THREAD

**Issue by bilicio** [githubsaturn/captainduckduck#315]
What is the problem?
At the end of the deployment through CLI it cames with this error:
```
Killed

{"code":137,"message":"The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 137"}
The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 137
----------------------
Deploy failed!
Error: {"code":137,"message":"The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 137"}
The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 137

Something bad happened. Cannot deploy "santander-app"
````

If applicable, content of `captain-definition` file:
the same as the site

Steps to reproduce the problem:
Using the CLI to deploy the app

Answers to the following questions where applicable:
- Your OS and version?
Ubuntu 16.04 
Docker 18

- RAM?
1gb

**Comment by githubsaturn** [comment]
There could more information in the logs before this line:
```
{"code":137,"message":"The command '/bin/sh -c npm install && npm cache clean --force'
```

Otherwise, if there is no other error/warning before that line, most likely, your machine is running out of memory. See these:

https://github.com/docker/compose/issues/1554

https://stackoverflow.com/questions/34674325/error-build-process-returned-exit-code-137-during-docker-build-on-tutum


To fix, either up your RAM to 2GB or more. Alternatively, if this is a frontend app, you can use something like this:
https://captainduckduck.com/docs/recipe-deploy-create-react-app.html

Even if it's a backend app, you can use this technique (with some modifications). Use the same technique to install your dependencies and make the app locally. Then use the advance version of node: https://captainduckduck.com/docs/captain-definition-file.html#advanced-version

Except, you should remove this line from the captain-definition: `RUN npm install && npm cache clean --force`.

**Comment by bilicio** [comment]
Thank you Kasra,
is there any easy way to deploy a compiled app instead of compiling all in the server, like upload a ready .tar file to the server?

**Comment by bilicio** [comment]
by the way, raising the ram to 1024 solved the problem! :)

**Comment by githubsaturn** [comment]
> is there any easy way to deploy a compiled app instead of compiling all in the server, like upload a ready .tar file to the server?

yes, it's in the sample that I included in the previous comment: https://captainduckduck.com/docs/recipe-deploy-create-react-app.html#deploy-with-captainduckduck

**Comment by bilicio** [comment]
thank you kasra!
One more thing please, in my app i work with socket on port 3031, and i tried to follow your guide to play with nginx without success. can you give me a tip on how to expose this port outside the captain for external access?

**Comment by bilicio** [comment]
I gotit !
I need to change captain-definition file with this ( "EXPOSE 3031") and create Port Mapping on captain to Server Public Port: 3031 and Container Port: 80. 👍
