### ISSUE TITLE
Support for Heroku-based applications

### ISSUE THREAD

**Issue by sr229** [githubsaturn/captainduckduck#325]
While this is intended to drop-in replace Heroku, there are some who can't leave the ease of use of Heroku. Since Captain is competing against the more matured SaaS in the market like Flynn, Cloud Foundry and Hephy (Deis fork for Kubernetes), it would make sense we should support a Heroku-llike workflow.

Under the hood, if you followed the Heroku architecture quite more intricately, you'll notice that:

- Heroku, to build applications, relies on Buildpacks, a set of shell scripts that provisions the tools needed by the application
- Heroku itself has a container registry, but it relies on remote/local registries based on which registry you defined it.
- Heroku uses a blobstore, aka the precompiled slug tarballs are stored there until they are replaced by newer ones. They rely as the PaaS's point of recovery when a container process dies, based on what was defined on the Procfile.

So, in light of that, we could literally replace Heroku with this if we were to have the following features:
 - A slugbuilder
 - A blobstore for precompiled slugs
 - Procfile support ( related to #37 ).
 - Resource control support out of the box (aka scaling the resources based on presets and user-defined resource limits).

To have a more in-line idea of what you can implement, I suggest looking at [OpenRuko](https://github.com/openruko) to check which was already implemented.

**Comment by githubsaturn** [comment]
I don' understand why this could be a burden. CaptainDuckDuck is not following Heroku structure 1:1. It follows Docker. Docker is a more generic form, and a defacto standard whereas Heroku is a commercially provided SaaS. Captain is just a thin wrapper around nginx and Docker. And it will stay like this rather than trying to copy a commercial product. To answer your points:
> A slugbuilder

Slugs are "Docker Images". CaptainDuckDuck builds your images from Dockerfiles.

> A blobstore for precompiled slugs

Blobstore is Dockerhub. It is free Docker Registry (repository) for public images. You can host your own Docker Registry for private images or you can use a 3rd party, or you can use CaptainDuckDuck (docker registry is bundled)

> Procfile support ( related to #37 ).

Procfiles are technically apps definitions. Captain provides a different recipe for app definitions.

> Resource control support out of the box (aka scaling the resources based on presets and user-defined resource limits).

It is already available through command line on Docker (and it plays nicely with CaptainDuckDuck). This will come to CaptainDuckDuck web dashboard soon.
