### ISSUE TITLE
Re-routing to a different (postgres) app

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#332]
I'm trying to figure out the best (idiot-proof) way of upgrading my postgres database within the captain environment.  My `postgres10` app is provisioned, with persistent data enabled, via the following simple `captain-definition` file (I use this to control which version of postgres is installed):

    {
      "schemaVersion": 1,
      "dockerfileLines": [
            "FROM postgres:10.6"
      ]
    }

Now I want to migrate to `postgres:11.1` with minimum database downtime, so I'm thinking that I could provision a separate `postgres11` app using:

    {
      "schemaVersion": 1,
      "dockerfileLines": [
            "FROM postgres:11.1"
      ]
    }

With both available in parallel I can then dump/restore generic SQL from `postgres10` into `postgres11`, with the `postgres10` still in operational use, and then switch traffic from `postgres10` to `postgres11` as quickly as possible`*`.

It's the switching that I'm unsure about.  At present, other apps in my docker swarm (and there are quite a number of them) access the postgres app internally via `srv-captain--postgres10`.  But it would take too much time to switch all of those apps to use `postgres11` instead, so I want a single, central switch.

Is there a way of achieving this e.g. using a custom nginx config in captain, so that I could e.g. use `srv-captain--database` (or some generic tag like that) within each app to access the database, and this is routed e.g. to `srv-captain--postgres10`... this would allow me simply to change that single switch over to `srv-captain--postgres11` when the data has been migrated across into that.

`*` note: this is not a mission-critical application so I'm not looking for an enterprise-level solution... I just want a simple "good-enough" solution that keeps the switchover time to a minimum, whilst accepting that some database updates might "fall through the cracks" during the switchover process... I just want to minimise such losses without going overboard.

**Comment by githubsaturn** [comment]
Unfortunately, Docker doesn't allow you to mangle its DNS entries. Plus, you cannot use nginx. Nginx runs for HTTP protocol, whereas Postgres runs on raw TCP socket.

As far as I understand, all you want is some sort of alias for Postgres container, so instead of changing your host for multiple apps, one at a time, you only change the alias mapping one time and all your apps point to the new container.

You can create a port forwarding container. Meaning that your architecture will be like:

```
                                       +-------------------+
+--------------+                       |                   |
|              |                       |                   |
|   App 1      +---------------------> |                   |
|              |                       |                   |
+--------------+                       |                   |
                                       |                   |
                                       |                   |
+--------------+                       |   PORT FORWARD    |
|              |                       |    CONTAINER      |
|   App 2      +---------------------> |                   |
|              |                       |                   |
+--------------+                       |                   |
                                       |                   |
                                       |                   |
+--------------+                       |                   |
|              |                       |                   |
|   App 3      +---------------------> |                   |
|              |                       |                   |
+--------------+                       +---------+---------+
                                                 |
                                                 |
                                                 v

                                       +-------------------+
                                       |                   |
                                       |      Postgres     |
                                       |                   |
                                       +-------------------+

```

The key to this architecture is a port forwarding container. And the tool to do this is `socat`. I have personally used this for debugging NodeJS process for CaptainDuckDuck and it wasn't easy to reach the working state. If your purpose is to learn this process, then try it out. Otherwise, you will end up spending more time than just manually updating the postgress address for each app.

Anyways, you decide to go with this approach, this is your workflow:
- Create a port forwarding container, e.g. see https://stackoverflow.com/questions/46099874/how-can-i-forward-a-port-from-one-docker-container-to-another
- Have the port forwarding container to forward all tcp connections from your desired port to `srv-captain--yourpostgres` app.
- Update one of your apps such that instead of using `srv-captain--yourpostgres` it uses `srv-captain--yourportforwarder`. Make sure it works.
- If everything is working, go and update all other apps.
- Now perform the postgres upgrade process.
- Now simply re-deploy your port forwarder app, now instead of forwarding to `srv-captain--yourpostgres`, forward to `srv-captain--yourpostgres-new`


Again, It's a fairly complex process. Make sure you experiment with it before applying your changes. I think your Dockerfile for your port forwarder ends up something like:
```
FROM alpine
RUN apk update && apk add socat
RUN echo "(socat -v  tcp-listen:5432,reuseaddr,fork tcp:srv-captain--yourpostgres:5432)" > /run.sh
CMD ["/bin/bash" , "-c" , "/run.sh" ]
```

The one above is just a starter point, it may be buggy and it probably needs modifications.

Disclaimer: I haven't used this technique myself for Postgres. But I have used it for other purposes.

**Comment by drmrbrewer** [comment]
Thanks, makes sense.  I'll give it a go.  It sounds similar to what I'm doing to forward requests to a node app running in my Cloud9 container (as described [here](https://github.com/githubsaturn/captainduckduck/issues/186#issuecomment-377948116)) where I have a very simple node app that just pipes the incoming request to the Cloud9 app.

**Comment by drmrbrewer** [comment]
I'm using [node-postgres](https://www.npmjs.com/package/pg) for handling access to the pg database.  Oddly, the solution you've given works flawlessly when the 'portforwarder' app is referenced via a public url in the config passed to node-postgres: `host: 'portforwarder.mydomain.com'`, but when I used the internal url `host: 'srv-captain--portforwarder'` I'm getting errors:

    Error: getaddrinfo EAI_AGAIN srv-captain--portforwarder srv-captain--portforwarder:5432

When using the same internal url to point directly to the database and not the port forwarder, i.e. `host: 'srv-captain--mypostgresdb'`, it works fine.

**Comment by githubsaturn** [comment]
This seems to be a Docker/NodeJS issue:
https://github.com/nodejs/node/issues/15780

**Comment by drmrbrewer** [comment]
aah...  I noted in particular the following comment in [this post](https://github.com/nodejs/node/issues/15780#issuecomment-425930255) (from the issue to which you linked):

> If you're using an image derived from alpine linux, there are known issues with the musl dns resolver.

So I switched from using `alpine` as the base and instead tried `ubuntu`, with the following `captain-definition`:

	{
		"schemaVersion": 1,
		"dockerfileLines": [			
			"FROM ubuntu:18.10",
			"RUN apt-get update && apt-get install -y socat",
			"RUN echo \"(socat -v tcp-listen:5432,reuseaddr,fork tcp:srv-captain--postgres:5432)\" > /run.sh",
			"RUN chmod +x /run.sh",
			"CMD [\"/bin/bash\" , \"-c\" , \"/run.sh\" ]"
		]
	}

Fingers crossed, seems to be working nicely!  Thank you so much, it is really appreciated.

**Comment by drmrbrewer** [comment]
Quick follow-up on this, for info.  Whilst the solution works, in practice I was finding that the port-forwarding container running `socat` was consuming unexpectedly high system CPU.  This surprises me as all this container is doing is forwarding packets; it's not doing any "real" work.  It didn't seem worth the extra CPU (== cost) merely for a benefit that is apparent over a very short time maybe once a year or so (when the postgres container is updated).  So for now I'm just changing the postgres host name in each app (via an environment variable change in captain console, so it's quick).  But with each exploration like this, a little more knowledge is gained!

**Comment by githubsaturn** [comment]
Wow! That's unexpected! Thanks for the info.
