### ISSUE TITLE
Trying to set up the CLI and getting `SSL is enabled for root. Too late to change your mind!`

### ISSUE THREAD

**Issue by freekrai** [githubsaturn/captainduckduck#41]
I'm trying the `captainduckduck serversetup` but I hit this response every time:

```
Error: 1000
Error: SSL is enabled for root. Too late to change your mind!
```

Also, if you enable force SSL, then you can't even get past the IP entry as the system tries to redirect http://IP:3000 to https://IP:3000 and fails.

**Comment by githubsaturn** [comment]
Of course! That's what force SSL means. You have to access it through your root domain. Did you follow steps outlined here?
https://github.com/githubsaturn/captainduckduck/wiki/Getting-Started

Right after installation of Captain, you should run `serversetup` which does following actions **in order**
- Connects to IP:3000
- Assigns a root domain to your Captain instance
- Enables SSL on your root domain
- Checks if SSL is successful, then forces SSL.

The setup process is intentionally left open for people who want to explore. Let's say, for some reason, you do not want to enable SSL. Then, instead of `captainduckduck serversetup` you manually go to dashboard and set root domain and simply use `captainduckduck login` on your local machine to attach to your server.
-----------

Specific to your case, once you enable your SSL, CaptainDuckDuck does not allow for root domain. This is by design and it's here to avoid back to back calls to let's encrypt and reassigning subdomains and whatnut. 

Now for your case, to get back to normal, SSH to your server, simply edit captain config file located at `/captain/config.conf` and set `forceSsl` to `false`. Then run
```
docker service update captain-captain --force
```

**Comment by freekrai** [comment]
Right makes sense, I guess if I set stuff up in the dashboard then I don’t need to use serversetup.

Will try to do some deployments next
