### ISSUE TITLE
http/2

### ISSUE THREAD

**Issue by dottodot** [githubsaturn/captainduckduck#44]
Is it possible to have http/2 support?

As far as I can tell nginx just needs it adding to the config such as 

```
listen 443 ssl http2
```
although I might wrong and it might not be that simple.

**Comment by benjaminboruff** [comment]
... and if `ssl`, then redirect `http` as per issue #2 ?

**Comment by githubsaturn** [comment]
@dottodot 
I was thinking of adding http2 as part of a bigger task: allowing user to *fully customize nginx server block*. That's because there won't be an end to all this kind of customizations that you can do with nginx. And we want to only add the most common ones to the interface, to keep things simple. But I'll keep this issue open to see if this is a common use case.

@benjaminboruff 
Focing HTTPS is already in the pipeline. If everything goes whell it'll be released before end of the year.

**Comment by Brun0AFK** [comment]
I think that this app definitely need custom nginx configuration.

**Comment by githubsaturn** [comment]
HTTP2 and much more using fully customizable nginx config in v0.4.0

https://github.com/githubsaturn/captainduckduck/releases/tag/v0.4.0

**Comment by valoricDe** [comment]
Hi @githubsaturn does it nowadays makes sense to have http2 as default in the default nginx configuration?

**Comment by githubsaturn** [comment]
I don't think it'd be a good idea... It's still not the default behavior for nginx, and nginx folks probably do their research to see if it's good idea to make it default or not.

**Comment by githubsaturn** [comment]
Actually, here it is: https://caniuse.com/http2

3.5% of users still don't have support for http2... that's not a negligible number.

**Comment by devxpy** [comment]
Interesting - my default caprover installation seems to support http2
<img width="690" alt="image" src="https://github.com/caprover/caprover/assets/19492893/445ce60d-e4ea-42b0-a54f-7f20c7bde467">

**Comment by devxpy** [comment]
Oh great its because of https://github.com/caprover/caprover/commit/60f4cdbb69921155b3c6206917792e62eb9c6234
