### ISSUE TITLE
Connect to new domain not same IP

### ISSUE THREAD

**Issue by jialutu** [githubsaturn/captainduckduck#72]
Hi, currently when you connect an app to a new domain, the new domain need to be set up to have the same IP as the captain domain. Would it be possible to add a feature to forego this check in case you want to use a reverse proxy such as Cloudflare please? Thanks

**Comment by githubsaturn** [comment]
No, the new domain does not need to have the same IP as Captain sever. But the request MUST finally come to Captain server (even with multiple reverse proxies in the way) - (is this the problem?) I don't understand why this is an issue. Can you please provide more details?

With reverse proxy. when you add a new domain the following steps happen:
1- Captain sends a request to www.myawesomeapp.com
2- Cloudfrare receives the request and forwards it Captain server
3- Captain receives the request and aknowledges the the domain is resolved to Captain (with or without some reverse proxy in the way)

In order to have it working, you will have to have Cloudfare setup ready before you attach a new domain.

I have not personally tested with the above setup, but surely, this is the "intented behaviour". If this is not how it's working, I'll have to look into it and improve the behavior. Can you please let me know if you tested with the setup described above and have the Cloudfare forwarding requests to Captain server in place and still have problem.

To test whether the Cloudfare forwarding works fine, when you have your setup ready, just visit `www.yourawesomeapp.com` and you should see the default Captain page which says "nothing here :/" Do you see this page?

**Comment by jialutu** [comment]
Maybe I was doing something wrong when I initially tried the setup. I had to set up the domain in godaddy and verified that it was working before changing it to use cloudflare. Since this is no longer an issue and I am unable to replicate it, I will close this issue. Thanks
