### ISSUE TITLE
502 Bad Gateway error with REST API

### ISSUE THREAD

**Issue by Derwaan** [githubsaturn/captainduckduck#76]
Hello!
I really enjoy your work with CaptainDuckDuck. Great job!

I am trying to use it with a node application. The back-end uses node.js and express and the front-end use Angular2. 
The client side do requests to the server side through the '/api' route. 
For example, if my application is accessible through `app.com`, the POST request for login an user will be to `app.com/api/login`.

But I keep having the 502 Bad Gateway error. 
Is this a way to configure my link between the client and the server side that will prevent this error? Did I miss some configurations? 

Thank you very much!

**Comment by githubsaturn** [comment]
The case you described works fine with Captain. Personally, I have multiple apps like that and they are all running fine. 

So you're saying your static files (front end) loads fine but backend POST request results in 502? This should not be possible. 

This seems to be your app bug,not Captain. You probably are not usi relative paths for your requests. Please provide a test app for further investigation. Alternatively, please include your webapp address so i can look into it.

**Comment by Derwaan** [comment]
Here are the simple code when user is authenticate.

The client side using Angular2:
```javascript
  authenticateUser(user) {
    let headers = new Headers();
    headers.append('Content-Type', 'application/json')

    return this.http.post('api/login', user, {
      headers: headers
    }).map(res => res.json())
  }
```

And for the server side (straightforward):
```javascript
router.post('/api/login', authController.authenticate)
```

It must be the URI used in the client side `api/login` that cause the error.

**Comment by githubsaturn** [comment]
This is not a CaptainDuckDuck related question. This is specific to your app. CaptainDuckDuck forwards all requests to `app.com` to your app without interfering with them. 

To reopen, if you have a repro case, please upload a tarball file of your application that exhibits the problem.

**Comment by futurekam** [comment]
This is happening on one of my captain apps and not the rest but here's the catch every third request is throwing a 502 error. I'm not sure what the root cause is because locally I can run my request at about 100 request /s but once deployed to my captain server It seems to fail every third request. I'm still investigating and this is the closing sounding to my case.

**Comment by buglinjo** [comment]
Have the same issue with AdonisJS deployment. It is running on `127.0.0.1:3333` I changed container http port to 3333 but still the same 502 error. I tried port mapping and still the same. I'm trying to fix this all freaking day lol, but nothing.

**Comment by githubsaturn** [comment]
Are you sure that your app is actually running? 502 means that nginx cannot connect to your app. Wrong binding port is one of the potential problems. To resolve:
- First change container http port to 3333 (like you did)
- Next, verify that your application is actually running. Go to the deploy tab of your app and view the logs. Your app might be erroring and restarting or not starting up properly.

**Comment by buglinjo** [comment]
That's what it sais in application logs.

**Comment by githubsaturn** [comment]
> That's what it sais in application logs.

Are you saying in your application log you see 502 error? Can you please copy and paste your application logs here?

**Comment by buglinjo** [comment]
This is my application log:
```
2019-04-08T22:44:26.890354034Z 
2019-04-08T22:44:26.890394993Z > adonis-api-app@4.1.0 start /usr/src/app
2019-04-08T22:44:26.890401146Z > node server.js
2019-04-08T22:44:26.890405113Z 
2019-04-08T22:44:27.265140778Z info: serving app on http://127.0.0.1:3333
```

**Comment by buglinjo** [comment]
One more thing, I tried adding HTTP Basic Auth and it asks for username and password and goes to cloudflare 502 page.

**Comment by githubsaturn** [comment]
If you can reproduce the issue with an open source project I can look into it.

My "guess" is that you need to change your binding to `0.0.0.0`


Regarding the HTTP auth, I believe it's a CloudFlare issue. They intercept the http request and manage the Basic Auth for you. You can disable the interception on CloudFlare interface by clicking on the orange cloud to turn it into a grey cloud.

**Comment by buglinjo** [comment]
Changed host IP to `0.0.0.0` it works like a charm! Thank you!

**Comment by prabirshrestha** [comment]
@githubsaturn Seems like this needs to be document in FAQ. https://caprover.com/docs/troubleshooting.html#successful-deploy-but-502-bad-gateway-error

I spent an hour debugging this 502 error and using `0.0.0.0` seems to work.

**Comment by direnc** [comment]
Where do I need to change the host IP?

**Comment by hamza-younas94** [comment]
> Where do I need to change the host IP?

in nginx configuration section

**Comment by Jonneal3** [comment]
This did NOT work for me. Does anyone have any other suggestions?

**Comment by mohdrashid1** [comment]
```
ERROR 2024-07-17T15:44:21.507751246Z [resource.labels.containerName: webapp-api] ' <h1> HTTP Error 500.30 - ANCM In-Process Start Failure </h1>\r\n' +
ERROR 2024-07-17T15:44:21.507768258Z [resource.labels.containerName: webapp-api] '\r\n' +
ERROR 2024-07-17T15:44:21.507778380Z [resource.labels.containerName: webapp-api] ' <h2> Common solutions to this issue: </h2><ul><li>The application failed to start</li><li>The application started but then stopped</li><li>The application started but threw an exception during startup</li></ul>\r\n' +
ERROR 2024-07-17T15:44:21.507784421Z [resource.labels.containerName: webapp-api] '\r\n' +
ERROR 2024-07-17T15:44:21.507790038Z [resource.labels.containerName: webapp-api] ' \r\n' +
ERROR 2024-07-17T15:44:21.507795816Z [resource.labels.containerName: webapp-api] '\r\n' +
ERROR 2024-07-17T15:44:21.507802540Z [resource.labels.containerName: webapp-api] ' <h2> Troubleshooting steps: </h2>\r\n' +
ERROR 2024-07-17T15:44:21.507812459Z [resource.labels.containerName: webapp-api] ' <ul>\r\n' +
ERROR 2024-07-17T15:44:21.507818392Z [resource.labels.containerName: webapp-api] ' <li> Check the system event log for error messages </li>\r\n' +
ERROR 2024-07-17T15:44:21.507824128Z [resource.labels.containerName: webapp-api] " <li> Enable logging the application process' stdout messages </li>\r\n" +
ERROR 2024-07-17T15:44:21.507829863Z [resource.labels.containerName: webapp-api] ' <li> Attach a debugger to the application process and inspect </li>\r\n' +
  _keepAliveTimeout: 0,
  insecureHTTPParser: undefined,
  keepAliveMsecs: 1000,
  ERROR 2024-07-17T15:44:21.506707105Z [resource.labels.containerName: webapp-api] response: {
ERROR 2024-07-17T15:44:21.506713270Z [resource.labels.containerName: webapp-api] status: 500,
ERROR 2024-07-17T15:44:21.506724253Z [resource.labels.containerName: webapp-api] statusText: 'Internal Server Error',
ERROR 2024-07-17T15:44:21.506022537Z [resource.labels.containerName: webapp-api] defaultPort: 443,
ERROR 2024-07-17T15:44:21.506028401Z [resource.labels.containerName: webapp-api] protocol: 'https:',
ERROR 2024-07-17T15:42:20.861101553Z [resource.labels.containerName: webapp-api] }
ERROR 2024-07-17T15:44:21.504950127Z [resource.labels.containerName: webapp-api] Error fetching the API: AxiosError: Request failed with status code 500 at settle (/app/node_modules/axios/dist/node/axios.cjs:1983:12) at IncomingMessage.handleStreamEnd (/app/node_modules/axios/dist/node/axios.cjs:3085:11) at IncomingMessage.emit (node:events:525:35) at endReadableNT (node:internal/streams/readable:1358:12) at processTicksAndRejections (node:internal/process/task_queues:83:21) at Axios.request (/app/node_modules/axios/dist/node/axios.cjs:4224:41) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async EmailService.readingSpec (/app/dist/notification/email_service.js:418:34) at async EmailService.sendPrivacyReport (/app/dist/notification/email_service.js:469:28) at async SensitiveDataService.processDocument (/app/dist/sensitive_data_service/sensitive_data.service.js:269:29) {
ERROR 2024-07-17T15:44:21.505071022Z [resource.labels.containerName: webapp-api] code: 'ERR_BAD_RESPONSE',
ERROR 2024-07-17T15:44:21.505076608Z [resource.labels.containerName: webapp-api] config: {
ERROR 2024-07-17T15:44:21.505221535Z [resource.labels.containerName: webapp-api] transitional: {
ERROR 2024-07-17T15:44:21.505230123Z [resource.labels.containerName: webapp-api] silentJSONParsing: true,
ERROR 2024-07-17T15:44:21.505235562Z [resource.labels.containerName: webapp-api] forcedJSONParsing: true,
ERROR 2024-07-17T15:44:21.505241112Z [resource.labels.containerName: webapp-api] clarifyTimeoutError: false
ERROR 2024-07-17T15:44:21.505246849Z [resource.labels.containerName: webapp-api] },
ERROR 2024-07-17T15:44:21.505253225Z [resource.labels.containerName: webapp-api] adapter: [ 'xhr', 'http', 'fetch' ],
ERROR 2024-07-17T15:44:21.505259837Z [resource.labels.containerName: webapp-api] transformRequest: [ [Function: transformRequest] ],
ERROR 2024-07-17T15:44:21.505265618Z [resource.labels.containerName: webapp-api] transformResponse: [ [Function: transformResponse] ],
ERROR 2024-07-17T15:44:21.505270953Z [resource.labels.containerName: webapp-api] timeout: 0,
ERROR 2024-07-17T15:42:20.861057619Z [resource.labels.containerName: webapp-api] },
ERROR 2024-07-17T15:42:20.861063535Z [resource.labels.containerName: webapp-api] cause: Error: certificate has expired at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34) at TLSSocket.emit (node:events:513:28) at TLSSocket._finishInit (node:_tls_wrap:953:8) at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
ERROR 2024-07-17T15:42:20.861090388Z [resource.labels.containerName: webapp-api] code: 'CERT_HAS_EXPIRED'
ERROR 2024-07-17T15:42:20.861096111Z [resource.labels.containerName: webapp-api] }
ERROR 2024-07-17T15:42:20.861101553Z [resource.labels.containerName: webapp-api] }





ERROR 2024-07-17T15:39:37.055237807Z [resource.labels.containerName: perfai-engine] },
ERROR 2024-07-17T15:39:37.055243893Z [resource.labels.containerName: perfai-engine] socketPath: undefined,
ERROR 2024-07-17T15:39:37.055249982Z [resource.labels.containerName: perfai-engine] method: 'POST',
ERROR 2024-07-17T15:39:37.055257154Z [resource.labels.containerName: perfai-engine] maxHeaderSize: undefined,
ERROR 2024-07-17T15:39:37.055263321Z [resource.labels.containerName: perfai-engine] insecureHTTPParser: undefined,
ERROR 2024-07-17T15:39:37.055269423Z [resource.labels.containerName: perfai-engine] path: '/api-analyzer/fetch-api-spec',
ERROR 2024-07-17T15:39:37.055275495Z [resource.labels.containerName: perfai-engine] _ended: true,
ERROR 2024-07-17T15:39:37.055282051Z [resource.labels.containerName: perfai-engine] res: IncomingMessage {
ERROR 2024-07-17T15:39:37.055288993Z [resource.labels.containerName: perfai-engine] _readableState: [ReadableState],
ERROR 2024-07-17T15:39:37.055301607Z [resource.labels.containerName: perfai-engine] _events: [Object: null prototype],
ERROR 2024-07-17T15:39:37.055313787Z [resource.labels.containerName: perfai-engine] _eventsCount: 4,
ERROR 2024-07-17T15:39:37.055321059Z [resource.labels.containerName: perfai-engine] _maxListeners: undefined,
ERROR 2024-07-17T15:39:37.055343082Z [resource.labels.containerName: perfai-engine] socket: [TLSSocket],
ERROR 2024-07-17T15:39:37.055349871Z [resource.labels.containerName: perfai-engine] httpVersionMajor: 1,
ERROR 2024-07-17T15:39:37.055356241Z [resource.labels.containerName: perfai-engine] httpVersionMinor: 1,
ERROR 2024-07-17T15:39:37.055362507Z [resource.labels.containerName: perfai-engine] httpVersion: '1.1',
ERROR 2024-07-17T15:39:37.055369587Z [resource.labels.containerName: perfai-engine] complete: true,
ERROR 2024-07-17T15:39:37.055376143Z [resource.labels.containerName: perfai-engine] rawHeaders: [Array],
ERROR 2024-07-17T15:39:37.055387644Z [resource.labels.containerName: perfai-engine] rawTrailers: [],
ERROR 2024-07-17T15:39:37.055399576Z [resource.labels.containerName: perfai-engine] aborted: false,
ERROR 2024-07-17T15:39:37.055407889Z [resource.labels.containerName: perfai-engine] upgrade: false,
ERROR 2024-07-17T15:39:37.055414310Z [resource.labels.containerName: perfai-engine] url: '',
ERROR 2024-07-17T15:39:37.055420523Z [resource.labels.containerName: perfai-engine] method: null,
ERROR 2024-07-17T15:39:37.055426958Z [resource.labels.containerName: perfai-engine] statusCode: 502,
ERROR 2024-07-17T15:39:37.055433121Z [resource.labels.containerName: perfai-engine] statusMessage: 'Bad Gateway',
ERROR 2024-07-17T15:39:37.055439371Z [resource.labels.containerName: perfai-engine] client: [TLSSocket],
ERROR 2024-07-17T15:39:37.055445722Z [resource.labels.containerName: perfai-engine] _consuming: false,
ERROR 2024-07-17T15:39:37.055451849Z [resource.labels.containerName: perfai-engine] _dumped: false,
ERROR 2024-07-17T15:39:37.055458097Z [resource.labels.containerName: perfai-engine] req: [Circular *1],
ERROR 2024-07-17T15:39:37.055465585Z [resource.labels.containerName: perfai-engine] responseUrl: 'https://privacy.ai.dev.perfai.ai/api-analyzer/fetch-api-spec',
ERROR 2024-07-17T15:39:37.055529982Z [resource.labels.containerName: perfai-engine] redirects: [],
ERROR 2024-07-17T15:39:37.049334386Z [resource.labels.containerName: perfai-engine] }
ERROR 2024-07-17T15:39:37.053966315Z [resource.labels.containerName: perfai-engine] Error updating field details with AI service: https://privacy.ai.dev.perfai.ai/api-analyzer/fetch-api-spec AxiosError: Request failed with status code 502 at settle (/app/node_modules/axios/dist/node/axios.cjs:1967:12) at IncomingMessage.handleStreamEnd (/app/node_modules/axios/dist/node/axios.cjs:3066:11) at IncomingMessage.emit (node:events:525:35) at endReadableNT (node:internal/streams/readable:1358:12) at processTicksAndRejections (node:internal/process/task_queues:83:21) at Axios.request (/app/node_modules/axios/dist/node/axios.cjs:3877:41) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) {
ERROR 2024-07-17T15:39:37.054107712Z [resource.labels.containerName: perfai-engine] code: 'ERR_BAD_RESPONSE',
ERROR 2024-07-17T15:39:37.054114006Z [resource.labels.containerName: perfai-engine] config: {
ERROR 2024-07-17T15:39:37.054121026Z [resource.labels.containerName: perfai-engine] transitional: {
ERROR 2024-07-17T15:39:37.054126952Z [resource.labels.containerName: perfai-engine] silentJSONParsing: true,
ERROR 2024-07-17T15:39:37.054132876Z [resource.labels.containerName: perfai-engine] forcedJSONParsing: true,
ERROR 2024-07-17T15:39:37.054138781Z [resource.labels.containerName: perfai-engine] clarifyTimeoutError: false
ERROR 2024-07-17T15:39:37.054145246Z [resource.labels.containerName: perfai-engine] },
ERROR 2024-07-17T15:39:37.054152116Z [resource.labels.containerName: perfai-engine] adapter: [ 'xhr', 'http' ],
ERROR 2024-07-17T15:39:37.054158867Z [resource.labels.containerName: perfai-engine] transformRequest: [ [Function: transformRequest] ],
ERROR 2024-07-17T15:39:37.054165172Z [resource.labels.containerName: perfai-engine] transformResponse: [ [Function: transformResponse] ],
ERROR 2024-07-17T15:39:37.054171281Z [resource.labels.containerName: perfai-engine] timeout: 0,


connection: 'close'
 statusCode: 502,
  statusMessage: 'Bad Gateway'
_keepAliveTimeout: 0,h
timeout: 0,
 clarifyTimeoutError
 code: 'ERR_BAD_RESPONSE'
 _maxListeners: undefined,
 ```
 
 im getting above 502 error in GKE Cluster i used GCE Ingress

**Comment by LBDeve** [comment]
Thanks in advance for the help -

Did everything up to this point except changing the 127.0.0.1 to 0.0.0.0  - don't know how to make this change.   Here's the app log:

~# docker service logs srv-captain--hkworg.1.0slf5g5r2ecg8ml117te1dsf0 --since 10m --follow
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | > hkw@1.1.0 start
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | > node ./index.js
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.207Z server-connect:setup:config {
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   port: 3001,
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   debug: true,
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   secret: '1IEDestkdpyqg09',
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   tmpFolder: '/usr/src/app/tmp',
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   abortOnDisconnect: false,
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   createApiRoutes: true,
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   compression: true,
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   redis: false,
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   cron: true,
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   static: { index: false },
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   session: {
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |     name: 'hkw.sid',
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |     resave: false,
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |     saveUninitialized: false,
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |     store: { '$type': 'memory', ttl: 86400000 }
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   },
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   cors: { origin: false, methods: 'GET,POST', credentials: true },
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   globals: {},
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   mail: {},
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   auth: {},
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   oauth: {},
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   db: {},
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   s3: {},
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   jwt: {},
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   stripe: {},
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    |   env: {}
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | }
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.487Z server-connect:setup:session init session store { '$type': 'memory', ttl: 86400000 }
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.519Z server-connect:setup:upload Upload middleware configured.
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.522Z server-connect:setup:routes Api route /api/qry/markerDetails(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.523Z server-connect:setup:routes Api route /api/qry/qryAllLocations(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.524Z server-connect:setup:routes Api route /api/qry/qryCigarSites_URLs(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.524Z server-connect:setup:routes Api route /api/qry/qryDHRgallery(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.525Z server-connect:setup:routes Api route /api/qry/qryPagination(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.526Z server-connect:setup:routes Api route /api/qry_boats/List(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.526Z server-connect:setup:routes Api route /api/qry_boats/a_test_index(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.527Z server-connect:setup:routes Api route /api/qry_boats/adv_boat_search_view(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.528Z server-connect:setup:routes Api route /api/qry_boats/advanced_boat_search(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.529Z server-connect:setup:routes Api route /api/qry_boats/advanced_search(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.529Z server-connect:setup:routes Api route /api/qry_boats/advanced_search_view_only(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.530Z server-connect:setup:routes Api route /api/qry_boats/archived_boats_1(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.531Z server-connect:setup:routes Api route /api/qry_boats/archived_nested_images(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.531Z server-connect:setup:routes Api route /api/qry_boats/archived_pagination(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.532Z server-connect:setup:routes Api route /api/qry_boats/boat_search(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.532Z server-connect:setup:routes Api route /api/qry_boats/m_boats_featured(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.533Z server-connect:setup:routes Api route /api/qry_boats/retrieve_archived_city_state(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.533Z server-connect:setup:routes Api route /api/qry_boats/sold_boats(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.534Z server-connect:setup:routes Api route /api/qry_boats/update_image_archive(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | 2024-08-01T23:23:25.535Z server-connect:setup:routes Api route /api/qry_boats/update_image_archive_copy(.json)? created
srv-captain--hkworg.1.0slf5g5r2ecg@ladyben    | App listening at http://localhost:3001

**Comment by jacoatvatfree** [comment]
I'm getting the same issue with an API gateway (graphql-mesh) trying to reach a REST API on the same caprover setup. I have a cluster of 2 servers set up though. When I do GET request from the browser to the API I get the correct response. But when the API Gateway tries a request it gets served the html of the Caprover 502 page. I don't have any errors in any logs from my apps. I also tried to use http://srv-captain--api and exposing ports etc, but no luck.

**Comment by githubsaturn** [comment]
This thread is for the CapRover API. 

What your seeing is a different issue. You can get the logs via `docker service logs srv-captain--yourrestapi` to see what's the issue.

**Comment by mebaysan** [comment]
https://github.com/caprover/caprover/issues/2006#issuecomment-2426288908

**Comment by R3D347HR4Y** [comment]
> For my case, nextjs is able to send request to /bank but it raises 502 on /. I solved by configuring the nginx.
> 
> ```nginx
> server {
>     # Other settings...
>     
>     # Increase buffer sizes for larger headers
>     proxy_buffer_size 128k;
>     proxy_buffers 4 256k;
>     proxy_busy_buffers_size 256k;
>     
>     # Continue with the rest of your configuration...
> }
> ```
> 
> [#2006 (comment)](https://github.com/caprover/caprover/issues/2006#issuecomment-2426288908)

Same problem with a svelte ssr app, adding this config in nginx custom config after proxy_pass $upstream; fixed it for me
