### ISSUE TITLE
Cleanup Docker

### ISSUE THREAD

**Issue by sidharthv96** [githubsaturn/captainduckduck#97]
My new years eve was turned into a day of mayhem when my production server running multiple apps crashed on me saying my disk was full.

When I checked, using the `df -h` command, I could see that only 30% of the space was used.
Later, I realised that with `df -i`, that my entire `inode`s were used up by docker.
It is a known issue with docker and overlay driver. The fact that I have been re-deploying apps 10s of times, that too some with node (requiring huge number of dependency files) must have caused the issue.

After I moved everything to another server and set it up again, I started to dig into my old server.
Simply running https://github.com/chadoe/docker-cleanup-volumes reduced my inode usage by 20%.

So, At least a part of my usage was garbage. When CaptainDuckDuck deploys a new version of the app, I suspect that docker doesn't do the cleanup properly.

Please integrate the commands specified [here](https://github.com/chadoe/docker-cleanup-volumes) to a maintenance task in CaptainDuckDuck which is run periodically.

**Comment by githubsaturn** [comment]
The proposed solution is clearly not a good idea to be done blindly by CaptainDuckDuck as the author writes:

> WARNING: Use at your own risk, always test with the --dry-run parameter first. If it's not compatible with your system or Docker version it will delete all your volumes.

Cleaning up volumes cannot be done blindly using the proposed script. Having said that, there are built-in commands in Docker now that take care of clean-up. `docker volume prune` cleans up the dangling volumes. But this is not a simple script to run. If there is a dead container with a volume, Docker still assumes that volume to be in-use! Even though the container is dead. 

The solution that works is to perform a container clean-up first, then perform a volume clean-up. BUT I need to do some thorough testing before implementing it as there might be another issue if a deploy is bogus and crashes a service continuous, Docker doesn't restart the service after multiple failures. This is good on itself. But the problem is that if we run a Docker clean up at that point in time, it might clean-up a useful volume which is really bad.

**Comment by sidharthv96** [comment]
> But the problem is that if we run a Docker clean up at that point in time, it might clean-up a useful volume which is really bad.

Yeah, this happened to me just now. 
Today, my apps stopped working and again said diskspace full. 
But I was closely monitoring my inodes usage and it was just around 34%. When I checked actual disk usage, it was 100%. So, containers weren't starting and captain was completely down. So I tried docker prune with images, containers and then volumes. Guess what, My postgres backend volume was pruned as it's container wasn't running...
Thankfully, I had backup that I had used to move data over from yesterday, So I ended up restoring that and lost one day's complete data.

**Comment by githubsaturn** [comment]
@sidharthv96 

Yup! You got lucky!

Anyways, as you "personally" experienced, pruning volumes are not a good idea to be done automatically. However, the reason that your file usage was too high wasn't necessarily orphaned volumes, it was mainly due to orphaned containers. In a recent commit (see below), I have added a container clean up task after each update. This will automatically clean up all log files and etc that are specific to a container. But this does not remove "volumes". Volume clean up needs to be done manually. And it should never be an everyday task as volumes once created they are supposed to be used forever until the app is deleted. I will add an optional volume cleanup to app delete pipeline in the future.

For now container clean-up is implemented: https://github.com/githubsaturn/captainduckduck/commit/baa6ecad2c2fc89e317249a496797d2601f59128

**Comment by githubsaturn** [comment]
https://github.com/githubsaturn/captainduckduck/wiki/Disk-Clean-Up
