### ISSUE TITLE
Docker logs rotate

### ISSUE THREAD

**Issue by sidharthv96** [githubsaturn/captainduckduck#98]
Today, my apps stopped working and again said diskspace full..
But I was closely monitoring my inodes usage and it was just around 34%. When I checked actual disk usage, it was 100%. So, containers weren't starting and captain was completely down. So I tried docker prune with images, containers and then volumes. Guess what, My postgres backend volume was pruned as it's container wasn't running...
Thankfully, I had backup that I had used to move data over from yesterday, So I ended up restoring that and lost one day's complete data.

When I manually tracked down where the usage was, I zeroed in on a <container-id>-log.json file which was 17GB in size!
After deleting that manually and restarting docker, everything was back to normal.
Please add logs rotate option in docker while creating new containers

**Comment by githubsaturn** [comment]
1.
I assume a majority of these logs belong to some dead containers. Once https://github.com/githubsaturn/captainduckduck/issues/97 is addressed, this problem automatically fades away

2.
There is an infinite number of Docker settings that can be exposed through Captain. Mirroring every single property is useless work. 

If there is a value that Captain does not expose for you to use, you can tweak it to match your need. This log config is one of them. You can simply set a cap for your service logs, and you know that Captain will not manipulate it. To do so, simply run:
```
 docker service update --log-driver json-file  --log-opt max-size=512m srv-captain--your-app-name
```

3.
Having said that, I agree that it's not a bad idea to default to 512MB (instead of unlimited) for log files and yet allow users to change it as they want.

**Comment by githubsaturn** [comment]
Default max size is now set to 512m and can be changed using the command above.
https://github.com/githubsaturn/captainduckduck/commit/baa6ecad2c2fc89e317249a496797d2601f59128
